VirtoCommerce/vc-module-experience-api

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateRepository.cs
> fix: fill Currency in CreateCart method

- src/XPurchase/VirtoCommerce.XPurchase/Extensions/ServiceCollectionExtensions.cs
> VP-2094 Fix DI for schemas

- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddOrUpdateCartPaymentCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/CartCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/MergeCartCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/MergeCartCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Extensions/ServiceCollectionExtensions.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/MergeCartType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
> Feature VP-2094 add merge cart mutation

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/Services/CartAvailMethodsService.cs
> Hotfix VP-2094: lifetime fix

- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
> Fix VP-2094

- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VP-3134
> VP-3134: Fix logo

- samples/VirtoCommerce.Exp.ExtensionSamples/_module.manifest
@yecli,  https://virtocommerce.atlassian.net/browse/VP-3134
> VP-3134: Fix sample logo

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartErrorDescriber.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddCartItemCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddCouponCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddOrUpdateCartPaymentCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddOrUpdateCartShipmentCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/CartCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeCartItemCommentCommandHangler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeCartItemPriceCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeCartItemQuantityCommandHangler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeCommentCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ClearCartCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ClearPaymentsCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ClearPaymentsCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ClearShipmentsCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ClearShipmentsCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/CreateCartCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RemoveCartItemCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RemoveCouponCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RemoveShipmentCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/CartType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
- src/XPurchase/VirtoCommerce.XPurchase/Specifications/CartHasPhysicalProductsSpecification.cs
- src/XPurchase/VirtoCommerce.XPurchase/Specifications/ProductIsBuyableSpecification.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartShipmentValidator.cs
> Feat VP-2094: add mutations, fix: some bugs

- .github/workflows/manual.yml
Added GitHub Action CI workflow to test a custom action
> VP-3754: Add module CI workflow

- .github/workflows/manual.yml
> workflow for modules

- .github/workflows/manual.yml
Reduced steps count;
Using a new action;
> refactoring

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/CategoryType.cs
> Fix VP-3927: Fix categories outlines

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/PropertyExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/PropertyType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/VariationType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
- tests/VirtoCommerce.ExperienceApiModule.Tests/Helpers/MoqHelper.cs
- tests/VirtoCommerce.XDigitalCatalog.Tests/Shemas/ProductTypeTests.cs
- tests/VirtoCommerce.XDigitalCatalog.Tests/Shemas/PropertyTypeTests.cs
- tests/VirtoCommerce.XDigitalCatalog.Tests/VirtoCommerce.XDigitalCatalog.Tests.csproj
https://virtocommerce.atlassian.net/browse/VP-4042
> VP-4042: Fix translated props

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/PropertyExtensions.cs
> VP-4042 Fix: implement non-dictionary property extraction

- src/XPurchase/VirtoCommerce.XPurchase/Queries/SearchCartQuery.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/CartQueryBase.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
Paging not working in user wishlist 
Use paging settings from query
> VP-4195: Fix broken paging

- src/XPurchase/VirtoCommerce.XPurchase/Authorization/CanAccessCartAuthorizationRequirement .cs
- src/XPurchase/VirtoCommerce.XPurchase/Extensions/ServiceCollectionExtensions.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
Cart search results not filtered by user that belongs to.
Add security
> VP-4132: Cart XAPI Security

- README.md
- docs/index.md
- mkdocs.yml
https://virtocommerce.atlassian.net/browse/VP-4286
> VP-4286 Docs: restructure

- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Aggregates/CartAggregateTests.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- tests/VirtoCommerce.XDigitalCatalog.Tests/Shemas/ProductTypeTests.cs
> Fix tests for CI

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ResolveFieldContextExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/ResolveFieldContextExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/DigitalCatalogSchema.cs
VP-6067 Catalog authentication/authorization scenarios
Make userId nullable for catalog queries
> VP-6067: Catalog authentication/authorization scenarios

- src/VirtoCommerce.ExperienceApiModule.Core/AnonymousUser.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateRepository.cs
The promotion (for special user group)
applies to product for ANONYMOUS user 
Fix cart search for anonymous user 
Fill customerId by new guid while searching anonymous cart
> Fix product discount calculation

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ResolveFieldContextExtensions.cs
- src/XPurchase/VirtoCommerce.XPurchase/Authorization/CanAccessCartAuthorizationRequirement .cs
- src/XPurchase/VirtoCommerce.XPurchase/Extensions/ResolveFieldContextExtensions.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
VP-6068 Complete cart authentication/authorization scenarios
Used authorization for single cart query. Insecurity for search cart query 
Rework authorization for cart queries 
Remove authorization from query for single cart 
Added authorization for search cart query
> VP-6068: Complete cart authentication authorization scenarios

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ResolveFieldContextExtensions.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Authorization/CanAccessOrderAuthorizationHandler.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Extensions/ServiceCollectionExtensions.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Queries/GetOrderQuery.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/InputChangeOrderStatusType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/InputPaymentInType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderSchema.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- tests/VirtoCommerce.ExperienceApiModule.XOrder.Tests/Authorization/OrderAuthorizationTests.cs
VP-6069 [X-API] Complete Order authentication/authorization scenarios
Authorization is absent 
Use authorization in queries and mutations
> VP-6069: Order authentication authorization scenarios

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/CategoryType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
Wrong object to serialize.
Change object.
> VP-6114: Fix slug and outlines responce

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ResolveFieldContextExtensions.cs
- src/XProfile/VirtoCommerce.XProfile/Authorization/CanEditOrganizationAuthorizationHandler.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/CreateContactCommand.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/CreateOrganizationCommand.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/DeleteContactCommand.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/DeleteUserCommand.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/UpdateContactAddressesCommand.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/UpdateRoleCommand.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/UpdateUserCommand.cs
- src/XProfile/VirtoCommerce.XProfile/Queries/GetContactByIdQuery.cs
- src/XProfile/VirtoCommerce.XProfile/Queries/GetContactByIdQueryHandler.cs
- src/XProfile/VirtoCommerce.XProfile/Queries/GetOrganizationByIdQuery.cs
- src/XProfile/VirtoCommerce.XProfile/Queries/GetOrganizationByIdQueryHandler.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputCreateContactType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputCreateOrganizationType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputCreateUserType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputDeleteContactType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputDeleteUserType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputUpdateContactAddressType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputUpdateContactType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputUpdateOrganizationType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputUpdateRoleType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputUpdateUserType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/ProfileSchema.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/UserType.cs
VP-6070 Complete Profile authentication authorization scenarios
Updated authorization
> VP-6070: Complete profile authentication and authorization scenarios

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ResolveFieldContextExtensions.cs
- src/XProfile/VirtoCommerce.XProfile/Authorization/CanEditOrganizationAuthorizationHandler.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/CreateContactCommand.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/CreateOrganizationCommand.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/DeleteContactCommand.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/DeleteUserCommand.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/UpdateContactAddressesCommand.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/UpdateRoleCommand.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/UpdateUserCommand.cs
- src/XProfile/VirtoCommerce.XProfile/Queries/GetContactByIdQuery.cs
- src/XProfile/VirtoCommerce.XProfile/Queries/GetContactByIdQueryHandler.cs
- src/XProfile/VirtoCommerce.XProfile/Queries/GetOrganizationByIdQuery.cs
- src/XProfile/VirtoCommerce.XProfile/Queries/GetOrganizationByIdQueryHandler.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputCreateContactType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputCreateOrganizationType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputCreateUserType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputDeleteContactType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputDeleteUserType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputUpdateContactAddressType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputUpdateContactType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputUpdateOrganizationType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputUpdateRoleType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputUpdateUserType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/ProfileSchema.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/UserType.cs
Reverts VirtoCommerce/vc-module-experience-api#84
Temporary revert to create a release
> Revert "VP-6070: Complete profile authentication and authorization scenarios"

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexFieldsMapper.cs
Incorrect mapping of variations for the product query.
Correct the mapping.
https://virtocommerce.atlassian.net/browse/VP-6153
> VP-6153: Fix mapping for the product query

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQuery.cs
Just added `ItemResponseGroup.ItemEditorialReviews` to the object request with `description` in `IncludeFields`.
> VP-6256: Add responce group

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsTaxMiddleware.cs
- tests/VirtoCommerce.XDigitalCatalog.Tests/Middlewares/EvalProductsTaxMiddlewareTest.cs
VP-4110 Respect currency param in the tax evaluation.
Seems evaluation doesn’t take into account requested currencies
Add tax middleware test
> VP-4110: Respect currency param in the tax evaluation

- src/XProfile/VirtoCommerce.XProfile/Authorization/CanEditOrganizationAuthorizationHandler.cs
VP-6070 Complete Profile authentication authorization scenarios
Access denied for user who try to update own info. UpdateUser mutation
Fix authorization check for update user mutation
> VP-6070: Fix Profile authorization 

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
- Add filtration
- Explicitly search for`"descriptions"` when determining response group
> VP-6256: Filter reviews ("product.descriptions") by culture name

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/AssetType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
Need to filter assets by `cultureName`
Add filter.
https://virtocommerce.atlassian.net/browse/VP-4109
> VP-6257: Implement assets filter

- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/SeoInfoType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexSearchRequestBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchCategoryQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/DigitalCatalogSchema.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/StoreCurrencyResolver.cs
- src/XProfile/VirtoCommerce.XProfile/Authorization/CanEditOrganizationAuthorizationHandler.cs
- src/XProfile/VirtoCommerce.XProfile/Queries/GetRoleQueryHandler.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/ProfileSchema.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/RoleType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/UserType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderLineItemType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderPaymentMethodType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderSchema.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/PaymentInType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
VP-6103 Create example queries for QA team
Some queries returned with errors 
Fix auth for the "user" query
Fix some query resolvers
> VP-6103 Example queries for QA

- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Aggregates/CartAggregateTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Helpers/Stubs/StubMember.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Helpers/Stubs/StubPaymentMethod.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Helpers/Stubs/StubPromotionResult.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Helpers/Stubs/StubShippingMethod.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Helpers/XPurchaseMoqHelper.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Validators/CartLineItemValidatorTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Validators/CartPaymentValidatorTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Validators/CartShipmentValidatorTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Validators/ItemQtyAdjustmentValidatorTests.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeCartItemQuantityCommandHangler.cs
- src/XPurchase/VirtoCommerce.XPurchase/ItemQtyAdjustment.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/ItemQtyAdjustmentValidator.cs
> VP-6390: Validation tests

- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputChangeCartItemCommentType.cs
VP-6103 Create example queries for QA team
Field comment of Int. When any integer number set then parsing error shown.
Fix field type
> VP-6103 Fix changeCartItem mutation 

- src/XPurchase/VirtoCommerce.XPurchase/Commands/ValidateCouponCommandHandler.cs
VP-6103: Create example queries for QA team
When trying to validate coupon see the error:  GraphQL.ExecutionError: Error trying to resolve validateCoupon
Fix coupon validation error if cart not found
> VP-6103: Create example queries for QA team

- docs/sorting_examples.postman_collection.json
- docs/x-catalog-reference.md
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexSearchRequestBuilder.cs
- tests/VirtoCommerce.ExperienceApiModule.Tests/Helpers/MoqHelper.cs
- tests/VirtoCommerce.ExperienceApiModule.Tests/Index/IndexSearchRequestBuilderTests.cs
VP-5985: Sort by scoring relevance and test all sorting scenarios
Set default sorting to score:DESC
Add sorting unit tests
> VP-5985: Sort by scoring relevance and test all sorting scenarios

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/FilterSyntaxMapper.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Mapping/FacetMappingProfile.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchCategoryQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/FacetTermType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/FilterFacetResultType.cs
https://virtocommerce.atlassian.net/browse/VP-6436
> #VP-6436 add outline name

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchCategoryQueryHandler.cs
> VP-6503: Categories list is empty after query

- src/VirtoCommerce.ExperienceApiModule.Core/Models/ProductPrice.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Models/TierPrice.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartProduct.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ValidateCouponCommandHandler.cs
Use cloned `CartAggregate` with the required coupon
> VP-6430: Implement proper coupon validation

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Specifications/CatalogProductIsAvailableSpecification.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Specifications/CatalogProductIsInStockSpecification.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/CartType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Specifications/ProductIsAvailableSpecification.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartLineItemValidator.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/NewCartItemValidator.cs
Replace creation of all domain specification from the "new" to the AbstractTypeFactory<> to satisfy the requirements for extensibility
> VP-6719: Create all specifications with abstract type factory

- src/XProfile/VirtoCommerce.XProfile/Authorization/ProfileAuthorizationHandler.cs
https://virtocommerce.atlassian.net/browse/VP-7027
https://virtocommerce.atlassian.net/browse/VP-6664
> VP-7027, VP-6664 add null check

- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Data/RecommendationsGatewayModule.Data.csproj
- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Web/RecommendationsGatewayModule.Web.csproj
- samples/VirtoCommerce.Exp.ExtensionSamples/VirtoCommerce.Exp.ExtensionSamples.csproj
- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XProfile/VirtoCommerce.XProfile/Authorization/ProfileAuthorizationHandler.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/CreateUserCommandHandler.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/SendVerifyEmailCommand.cs
- src/XProfile/VirtoCommerce.XProfile/Commands/SendVerifyEmailCommandHandler.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputSendVerifyEmailType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/ProfileSchema.cs
- src/XProfile/VirtoCommerce.XProfile/VirtoCommerce.ExperienceApiModule.XProfile.csproj
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
sending verificaiton email by mutation and after creating new user
https://virtocommerce.atlassian.net/browse/VP-6893
> VP-6893 add send verification email mutation

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateRepository.cs
This should improve XAPI performance and reduce deadlock cases.
> VP-6911: Delete cart softly

- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddCartItemsCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddCartItemsCommandHandler.cs
https://virtocommerce.atlassian.net/browse/PT-396
> PT-396 rename add items request property

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/AssetType.cs
Also, publish IsInherited to allow users to know is asset inherited or not
https://virtocommerce.atlassian.net/browse/PT-146
> PT-334: Make asset id nullable to avoid crash for inherited assets

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/VariationType.cs
https://virtocommerce.atlassian.net/browse/PT-280
> PT-447: Add name of variation to VariationType

- src/VirtoCommerce.ExperienceApiModule.Core/Models/ProductPrice.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Mapping/ProductMappingProfile.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/PriceType.cs
Also add StartDate, EndDate to the price GraphQL type
> PT-330: Fix product price validFrom/validTo dates values

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/OutlineExtensions.cs
Jira: https://virtocommerce.atlassian.net/browse/PT-56
Bug: https://virtocommerce.atlassian.net/browse/PT-483
> PT-483: Fix null reference exception in breadcrumbs calculation

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQuery.cs
Jira: https://virtocommerce.atlassian.net/browse/PT-56
> PT-498: Fix response group selector

- Directory.Build.props
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
Jira: https://virtocommerce.atlassian.net/browse/PT-46
> PT-46: XAPI Release 1.0

- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
https://virtocommerce.atlassian.net/browse/PT-604
> PT-605 remove redundant clearCart mutation argument

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQuery.cs
https://virtocommerce.atlassian.net/browse/PT-763
https://virtocommerce.atlassian.net/browse/PT-762
> PT-763 PT-762 add seoInfos to product request when querying breadcrumbs

- src/XProfile/VirtoCommerce.XProfile/Commands/SearchMembersQueryHandler.cs
https://virtocommerce.atlassian.net/browse/PT-1469
> PT-1469: Include not only top level members into search results

- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Core/Schemas/ProductRecommendationSchema.cs
- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Web/Module.cs
- samples/VirtoCommerce.Exp.ExtensionSamples/UseCases/TypeExtension/Schemas/CustomSchema.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ResolveFieldContextExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/CurrencyType.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/TaxLineType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Facets/FacetResult.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Facets/FacetTerm.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexSearchRequestBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsInventoryMiddleware.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/DigitalCatalogSchema.cs
https://virtocommerce.atlassian.net/browse/PT-1624
> PT-1624: Check todos

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateRepository.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartProduct.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/LineItemType.cs
https://virtocommerce.atlassian.net/browse/PT-830
> PT-1673 add FulfillmentCenter Id and Name to Line item

- samples/VirtoCommerce.Exp.ExtensionSamples/UseCases/TypeExtension/Schemas/CartType2.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Helpers/QueryArgumentPresets.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Services/DynamicPropertyResolverService.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Services/IDynamicPropertyResolverService.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/CartType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/LineItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PaymentType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/ShipmentType.cs
https://virtocommerce.atlassian.net/browse/PT-1103
> PT-1104 add Dynamic properties to Cart types

- src/VirtoCommerce.ExperienceApiModule.Core/Services/DynamicPropertyResolverService.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateResponseGroup.cs
- src/XPurchase/VirtoCommerce.XPurchase/Queries/CartQueryBase.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/CartType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/LineItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PaymentType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/ShipmentType.cs
https://virtocommerce.atlassian.net/browse/PT-1103
> PT-1763 Added Dynamic Property response group to cart

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/CustomerOrderType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderLineItemType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderShipmentType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/PaymentInType.cs
https://virtocommerce.atlassian.net/browse/PT-1166
> PT-1170 add Dynamic Properties to Order

- docs/x-purchase-cart-reference.md
https://virtocommerce.atlassian.net/browse/PT-411
> PT-411 Add CartAddress documentation

- src/VirtoCommerce.ExperienceApiModule.Core/Services/DynamicPropertyUpdaterService.cs
https://virtocommerce.atlassian.net/browse/PT-2041
> PT-2041 Prevent adding locale for Dictionary property values on Update

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/OutlineExtensions.cs
https://virtocommerce.atlassian.net/browse/PT-2232
> PT-2233: Fix outline titles for categories/products

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexSearchRequestBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQueryHandler.cs
Use the folowing filter syntax to search variations
```json
filter: "status:hidden is:variation"
```
> PT-2588: Allow to use 'status' term in filter expression

- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Data/RecommendationsGatewayModule.Data.csproj
- samples/VirtoCommerce.Exp.ExtensionSamples/VirtoCommerce.Exp.ExtensionSamples.csproj
- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/VirtoCommerce.ExperienceApiModule.Web.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XProfile/VirtoCommerce.XProfile/VirtoCommerce.ExperienceApiModule.XProfile.csproj
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/CustomerOrderSearchCriteriaBuilder.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Queries/SearchOrderQueryHandler.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
https://virtocommerce.atlassian.net/browse/PT-1184
> PT-1187 Change search order to indexed search service

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/PropertyExtensions.cs
- tests/VirtoCommerce.XDigitalCatalog.Tests/Shemas/ProductTypeTests.cs
https://virtocommerce.atlassian.net/browse/PT-2228
https://virtocommerce.atlassian.net/browse/PT-2291
> PT-2230, PT-2292 fix localization issues in Catalog properties

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Breadcrumbs/Breadcrumb.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/OutlineExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/BreadcrumbsType.cs
https://virtocommerce.atlassian.net/browse/PT-2639
> PT-2640: Add SemanticUrl to Breadcrumb

- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Data/RecommendationsGatewayModule.Data.csproj
- samples/VirtoCommerce.Exp.ExtensionSamples/VirtoCommerce.Exp.ExtensionSamples.csproj
- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/GetCountriesQuery.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/GetCountriesQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/GetCountriesResponse.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/GetRegionsQuery.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/GetRegionsResponse.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/CoreSchema.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/CountryRegionType.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/CountryType.cs
- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XProfile/VirtoCommerce.XProfile/VirtoCommerce.ExperienceApiModule.XProfile.csproj
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
> VDS-2326 Add query for loading country list

- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Core/RecommendationsGatewayModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Mapping/PropertyMappingProfile.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/PropertySearchCriteriaBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/LoadPropertiesQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/LoadPropertiesQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/LoadPropertiesResponse.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchPropertiesQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchPropertiesQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchPropertiesResponse.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchPropertyDictionaryItemQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchPropertyDictionaryItemQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchPropertyDictionaryItemResponse.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/CategoryType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/DigitalCatalogSchema.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/PropertyDictionaryItemType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/PropertyType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/VirtoCommerce.ExperienceApiModule.Web.csproj
- tests/VirtoCommerce.ExperienceApiModule.Tests/VirtoCommerce.ExperienceApiModule.Tests.csproj
- tests/VirtoCommerce.XDigitalCatalog.Tests/Shemas/PropertyTypeTests.cs
Add properties, property queries
> PT-2388: Extend xAPI GraphQL schema with catalog properties metadata

- src/VirtoCommerce.ExperienceApiModule.Core/Queries/PasswordValidationQuery.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/PasswordValidationQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/PasswordValidationResponse.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/CoreSchema.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/PasswordValidationResult.cs
- src/VirtoCommerce.ExperienceApiModule.Web/Module.cs
Add query for password validation
> VDS-2474: Add password validation query

- src/VirtoCommerce.ExperienceApiModule.Core/Models/IdentityErrorInfo.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/PasswordValidationQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/PasswordValidationResponse.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/PasswordValidationErrorType.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/PasswordValidationType.cs
> VDS-2473 Return error info array instead of erros codes for pswd validation query

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
Fix exception when validating coupon for anonymous cart
> PT-3363 fix NRE for anonymous cart clone

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Mapping/FacetMappingProfile.cs
PT-3616: Fix label mapping for TermFacet
https://virtocommerce.atlassian.net/browse/PT-3616
> PT-3616: Fix label mapping for TermFacet

- src/XProfile/VirtoCommerce.XProfile/Schemas/ProfileSchema.cs
> VDS-2638: User could edit own company

- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/CoreSchema.cs
Return Regions by Country Code
> PT-3318 GetRegions query

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/IHasLanguageExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/FacetsExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Mapping/FacetMappingProfile.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/DigitalCatalogSchema.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/FacetInterface.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/FilterFacetResultType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/RangeFacetResultType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/TermFacetResultType.cs
Proper facets handling for multivalue, multilanguage properties.
Add localized label to the facet. Repair facet term label to show proper value accordingly to passed culture.
https://virtocommerce.atlassian.net/browse/PT-3044
> PT-3045: Facets for multivalue, multilanguage properties

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/CategoryType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
Seems there is a bug related to https://virtocommerce.atlassian.net/browse/PT-3718
https://virtocommerce.atlassian.net/browse/PT-3718
> PT-3719: Use abstract factory to create SeoInfo instances

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/RemoveNullCatalogProductsMiddleware.cs
Remove phantom products from the search results. They exist only in the index.
> PT-3537: Add RemoveNullCatalogProductsMiddleware

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/CurrencyExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XProfile/VirtoCommerce.XProfile/VirtoCommerce.ExperienceApiModule.XProfile.csproj
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
- tests/VirtoCommerce.ExperienceApiModule.Tests/Helpers/MoqHelper.cs
- tests/VirtoCommerce.XDigitalCatalog.Tests/Middlewares/EvalProductsTaxMiddlewareTest.cs
> PT-3626: Fix currency cloning and update dependencies

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/CurrencyExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ResolveFieldContextExtensions.cs
quickfix for failing xapi query
> PT-3126: Fix currencies convertion

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/PaymentsSearchCriteriaBuilder.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderPaymentMethodType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/PaymentInType.cs
> PT-3126: Add more fields to PaymentInType

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ResolveFieldContextExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/DiscountType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
- tests/VirtoCommerce.ExperienceApiModule.Tests/Schemas/DiscountTypeTests.cs
https://virtocommerce.atlassian.net/browse/PT-3990
Artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_1.27.0-pr-198.zip
> PT-3990: Extend DiscountType with money fields

- src/XProfile/VirtoCommerce.XProfile/Schemas/InputCreateUserType.cs
> VDS-2834: Add password expired property

- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/AddressType.cs
- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputMemberAddressType.cs
- src/XProfile/VirtoCommerce.XProfile/VirtoCommerce.ExperienceApiModule.XProfile.csproj
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/InputOrderAddressType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputAddressType.cs
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
Extend Address with OuterId property
https://virtocommerce.atlassian.net/browse/PT-4060
> PT-4060: Extend Address with OuterId property

- src/VirtoCommerce.ExperienceApiModule.Core/Index/IFilterExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/FacetsExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexSearchRequestBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQueryHandler.cs
Repair facet search by price range.
Rework for term facet search to avoid potential bugs.
https://virtocommerce.atlassian.net/browse/PT-2976
> PT-2976: Repair facet search by price range

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQueryHandler.cs
Show all available facets when no facet is selected by the user
https://virtocommerce.atlassian.net/browse/PT-4493
> PT-4493: Fix empty termfacets

- src/XProfile/VirtoCommerce.XProfile/Schemas/InputCreateUserType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/InputUpdateUserType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/ProfileSchema.cs
> PT-4170: Remove isAdministrator from mutations

- docs/x-api-extensions.md
- samples/VirtoCommerce.Exp.ExtensionSamples/Module.cs
- samples/VirtoCommerce.Exp.ExtensionSamples/UseCases/TypeExtension/Schemas/CartType2.cs
- samples/VirtoCommerce.Exp.ExtensionSamples/UseCases/TypeExtension/Validators/CartValidator2.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Aggregates/CartAggregateTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Repositories/CartAggregateRepositoryTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Validators/CartLineItemValidatorTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Validators/CartPaymentValidatorTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Validators/CartShipmentValidatorTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Validators/CartValidatorTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Validators/ChangeCartItemPriceValidatorTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Validators/ItemQtyAdjustmentValidatorTests.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateRepository.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeCartItemPriceCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeCartItemQuantityCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/ItemQtyAdjustment.cs
- src/XPurchase/VirtoCommerce.XPurchase/PriceAdjustment.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/CartType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartLineItemValidator.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartPaymentValidator.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartShipmentValidator.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartValidationContext.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartValidationContextFactory.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartValidator.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/ChangeCartItemPriceValidator.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/ItemQtyAdjustmentValidator.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/LineItemValidationContext.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/PaymentValidationContext.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/ShipmentValidationContext.cs
https://virtocommerce.atlassian.net/browse/PT-4083
> PT-4083: Add an ability for extending cart validation logic

- src/VirtoCommerce.ExperienceApiModule.Core/Services/DynamicPropertyResolverService.cs
Fix dynamic property resolve for non-existing cart
https://virtocommerce.atlassian.net/browse/PT-4480
> PT-4480: Fix dynamic property resolve for non-existing cart

- src/XProfile/VirtoCommerce.XProfile/Schemas/ContactType.cs
> VDS-3021: Use deep search

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Services/IUserManagerCore.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Services/UserManagerCore.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/ContactType.cs
- src/XProfile/VirtoCommerce.XProfile/Schemas/UserType.cs
> VDS-2886: Add locked state property

- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/CustomGraphQLExecuter.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/IgnorePlainGraphQLTelemetryProcessor.cs
- src/VirtoCommerce.ExperienceApiModule.Web/Module.cs
Requests:
Failures:
Exceptions:
> PT-4321 Add AppInsights request telemetry

- README.md
> PT-4326: Add AppInsights integration doc

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsInventoryMiddleware.cs
> PT-4757: Add paging to EvalProductsInventoryMiddleware

- src/VirtoCommerce.ExperienceApiModule.Core/Queries/DynamicPropertyQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/DynamicPropertySearchCriteriaBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/GetDynamicPropertyQuery.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/SearchDynamicPropertiesQuery.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/DynamicPropertySchema.cs
> PT-4457: Add ObjectType argument to DynamicProperty and DynamicProperties queries

- VirtoCommerce.ExperienceApiModule.sln
- src/VirtoCommerce.ExperienceApiModule.Web/Module.cs
- src/VirtoCommerce.ExperienceApiModule.Web/VirtoCommerce.ExperienceApiModule.Web.csproj
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS.Tests/Handlers/GetMenusQueryHandlerTests.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS.Tests/VirtoCommerce.ExperienceApiModule.XCMS.Tests.csproj
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Extensions/ServiceCollectionExtensions.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetMenusQuery.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetMenusQueryHandler.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetMenusResponse.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Schemas/ContentSchema.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Schemas/MenuLinkListType.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Schemas/MenuLinkType.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/VirtoCommerce.ExperienceApiModule.XCMS.csproj
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/XCMSAnchor.cs
> ST-62: Add Menus query, CMS domain

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/PropertyType.cs
> PT-4928: Fix incorrect ValueType for PropertyType

- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Aggregates/CartAggregateTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Helpers/Stubs/StubPromotionReward.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Repositories/CartAggregateRepositoryTests.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
> PT-5331: Add CartAggregate tests

- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Core/RecommendationsGatewayModule.Core.csproj
- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Data/RecommendationsGatewayModule.Data.csproj
- samples/VirtoCommerce.Exp.ExtensionSamples/VirtoCommerce.Exp.ExtensionSamples.csproj
- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchVideoQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchVideoQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchVideoQueryResponse.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/VideoType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/VirtoCommerce.ExperienceApiModule.Web.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XProfile/VirtoCommerce.XProfile/VirtoCommerce.ExperienceApiModule.XProfile.csproj
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- tests/VirtoCommerce.ExperienceApiModule.Tests/VirtoCommerce.ExperienceApiModule.Tests.csproj
> PT-5108: Add Videos connection to ProductType

- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Core/RecommendationsGatewayModule.Core.csproj
- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Data/RecommendationsGatewayModule.Data.csproj
- samples/VirtoCommerce.Exp.ExtensionSamples/VirtoCommerce.Exp.ExtensionSamples.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexFieldsMapper.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchCategoryQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/CategoryDescriptionType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/CategoryType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/VirtoCommerce.ExperienceApiModule.Web.csproj
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- tests/VirtoCommerce.ExperienceApiModule.Tests/VirtoCommerce.ExperienceApiModule.Tests.csproj
XAPI Extend Category with Descriptions
https://virtocommerce.atlassian.net/browse/PT-4914
> PT-4914: XAPI Extend Category with Descriptions

- docs/x-catalog-reference.md
> PT-5113: Fix ProductType doc

- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Handlers/MoveWishListItemCommandHandlerTests.cs
- src/XPurchase/VirtoCommerce.XPurchase/Authorization/CanAccessCartAuthorizationRequirement .cs
- src/XPurchase/VirtoCommerce.XPurchase/CartSearchCriteriaBuilder.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddWishlistItemCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddWishlistItemCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/CreateWishlistCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/CreateWishlistCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/MoveWishListItemCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/MoveWishlistItemCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RemoveWishlistCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RemoveWishlistCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RemoveWishlistItemCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RemoveWishlistItemCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RenameWishlistCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RenameWishlistCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/WishlistCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Queries/GetWishlistQuery.cs
- src/XPurchase/VirtoCommerce.XPurchase/Queries/GetWishlistQueryHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Queries/SearchWishlistQuery.cs
- src/XPurchase/VirtoCommerce.XPurchase/Queries/SearchWishlistQueryHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputAddWishlistItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputCreateWishlistType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputMoveWishlistItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputRemoveWishlistItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputRemoveWishlistType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputRenameWishlistType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/WishlistType.cs
- src/XPurchase/VirtoCommerce.XPurchase/XPurchaseConstants.cs
https://virtocommerce.atlassian.net/browse/ST-144
> ST-144: Add Wishlist queries and mutations

- src/XProfile/VirtoCommerce.XProfile/Schemas/UserType.cs
https://virtocommerce.atlassian.net/browse/ST-323
> ST-323: Return null Contact in 'me' query

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsPricesMiddleware.cs
https://virtocommerce.atlassian.net/browse/PT-5490
> PT-5490: Use store and catalog Id in price evaluation

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
https://virtocommerce.atlassian.net/browse/ST-607
> ST-607: Add minQuantity, maxQuantity to ProductType

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Specifications/CatalogProductIsAvailableSpecification.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Specifications/CatalogProductIsInStockSpecification.cs
- tests/VirtoCommerce.XDigitalCatalog.Tests/Helpers/XDigitalCatalogMoqHelper.cs
- tests/VirtoCommerce.XDigitalCatalog.Tests/Specifications/CatalogProductIsAvailableSpecificationTests.cs
- tests/VirtoCommerce.XDigitalCatalog.Tests/Specifications/CatalogProductIsBuyableSpecificationTests.cs
https://virtocommerce.atlassian.net/browse/ST-529
> ST-529: Fix product with 0 items in stock being available

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/CustomerOrderAggregate.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Validators/ProcessPaymentRequestValidator.cs
- tests/VirtoCommerce.ExperienceApiModule.XOrder.Tests/ProcessPaymentRequestValidatorTests.cs
Process payment request validation is fixed and unit tests are added
> PT-5293: Process payment request validation is fixed

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
> ST-638: Add Master Product field to Product Type

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/VariationType.cs
https://virtocommerce.atlassian.net/browse/ST-666
> ST-666: Add Min Max quantity to Variation Type

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/CustomerOrderType.cs
> ST-452: Add Discount property to CustomerOrderType

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangePurchaseOrderNumberCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangePurchaseOrderNumberCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/CartType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputChangePurchaseOrderNumber.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
https://virtocommerce.atlassian.net/browse/ST-472
> ST-472: Add Change Purchase Order Number mutation in Cart

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexSearchRequestBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
> ST-378: Use Currency in sort by Prices in Search Product

- src/XPurchase/VirtoCommerce.XPurchase/Authorization/CanAccessCartAuthorizationRequirement .cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
Authorization is added for all purchase mutations
https://virtocommerce.atlassian.net/browse/PT-6223
> PT-6223: Authorization is added for all purchase mutations

- .github/workflows/main_postman.yml
> install globaltool 2.1.0-alpha

- .github/workflows/main_postman.yml
> use net6 in workflow

- .github/workflows/katalon_e2e.yml
> change version .net to 6.0.x

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexFieldsMapper.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
- src/VirtoCommerce.ExperienceApiModule.Web/Extensions/HttpContextExtensions.cs
- src/XPurchase/VirtoCommerce.XPurchase/Authorization/CanAccessCartAuthorizationRequirement .cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
https://virtocommerce.atlassian.net/browse/ST-720
> ST-720, ST-661: Fix authorization in Purchase schema, Add HasVariations Flag, Fix BrandName field

- src/XPurchase/VirtoCommerce.XPurchase/BulkCartResult.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartErrorDescriber.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartValidationError.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddCartItemsBulkCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddCartItemsBulkCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/NewBulkCartItem.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/BulkCartType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputAddBulkItemsType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputNewBulkItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
https://virtocommerce.atlassian.net/browse/ST-914
> ST-914: Add addBulkItemsCart mutation

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartLineItemValidator.cs
https://virtocommerce.atlassian.net/browse/ST-711
> ST-711: Fix CartValidation ruleset

- .github/workflows/katalon_e2e.yml
> up katalon version to 8.2.5

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexSearchRequestBuilder.cs
Building of facets search query filters is fixed
https://virtocommerce.atlassian.net/browse/PT-6513
> PT-6513: Building of facets search query filters is fixed

- docs/x-api-extensions.md
> PT-5457: Add extensibility restrictions note

- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeCartItemQuantityCommandHandler.cs
Removing line items with zero quantity from cart
https://virtocommerce.atlassian.net/browse/PT-6075
> PT-6075: Removing line items with zero quantity from cart

- .github/workflows/main_postman.yml
> add newman reporter

- .github/workflows/main_postman.yml
> newman action as run

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderPaymentMethodType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PaymentMethodType.cs
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
https://virtocommerce.atlassian.net/browse/PT-7185
> PT-6844: Add Payment Type description field

- docs/x-purchase-cart-reference.md
- src/XPurchase/VirtoCommerce.XPurchase/BulkCartAggregateResult.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddWishlistBulkItemCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddWishlistBulkItemCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/BulkWishlistType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputAddWishlistBulkItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputAddWishlistItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
Add mutation addWishlistBulkItem
https://virtocommerce.atlassian.net/browse/PT-7083
> PT-7083: Add mutation addWishlistBulkItem

- docs/x-catalog-reference.md
> PT-7342: fix documentation

- docs/x-catalog-reference.md
> PT-7325: add tier pricing example

- .github/workflows/module-sample-ci.yml
- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Web/Module.cs
https://virtocommerce.atlassian.net/browse/PT-7292
> PT-7292: Remove redundant BuildServiceProvider from the module startup

- src/VirtoCommerce.ExperienceApiModule.Core/Helpers/Constants.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/CreateOrderFromCartCommandHandler.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Handlers/CreateOrderFromCartCommandHandlerTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Validators/CartLineItemValidatorTests.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartErrorDescriber.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartLineItemValidator.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/ItemQtyAdjustmentValidator.cs
https://virtocommerce.atlassian.net/browse/PT-7399
https://virtocommerce.atlassian.net/browse/PT-7404
> PT-7399, PT-7404: add create order validation, min/max product qty validation

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
https://virtocommerce.atlassian.net/browse/PT-7431
> PT-7431: fix tier prices for added line item

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/VariationType.cs
Jira-link:
https://virtocommerce.atlassian.net/browse/ST-2039
Artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.211.0-pr-305.zip
> ST-2039: return a slug for a VariationType

- Directory.Build.props
- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Core/RecommendationsGatewayModule.Core.csproj
- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Data/RecommendationsGatewayModule.Data.csproj
- samples/VirtoCommerce.Exp.ExtensionSamples/VirtoCommerce.Exp.ExtensionSamples.csproj
- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Mapping/FacetMappingProfile.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/VirtoCommerce.ExperienceApiModule.Web.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Aggregates/CartAggregateTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Helpers/XPurchaseMoqHelper.cs
- tests/VirtoCommerce.ExperienceApiModule.Tests/VirtoCommerce.ExperienceApiModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-6936
> PT-6936: convert upper/lower bounds inclusion flags from Catalog's aggregation items

- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartLineItemValidator.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/ItemQtyAdjustmentValidator.cs
https://virtocommerce.atlassian.net/browse/PT-7692
> PT-7692: account for 0 in max qty check

- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
Fix resolve 'listPrice' in addItemsCart mutation
https://virtocommerce.atlassian.net/browse/PT-7587
> PT-7587: Fix resolve 'listPrice' in addItemsCart mutation

- .github/workflows/main.yml
> Add katalon test 

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/InputOrderShipmentType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderShipmentType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
Order shipment schema is extended with tracking information
https://virtocommerce.atlassian.net/browse/PT-7920
> PT-7920: Order shipment schema is extended with tracking information

- docs/x-purchase-order-reference.md
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/AddOrUpdateOrderPaymentCommand.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/AddOrUpdateOrderPaymentCommandHandler.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/CustomerOrderAggregate.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Models/ExpOrderAddress.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Models/ExpOrderPayment.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/OrderErrorDescriber.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/InputAddOrUpdateOrderPaymentType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/InputOrderAddressType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/InputOrderPaymentType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/InputPaymentInType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderSchema.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Validators/OrderPaymentValidationContext.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Validators/OrderPaymentValidator.cs
- tests/VirtoCommerce.ExperienceApiModule.XOrder.Tests/Handlers/AddOrUpdateOrderPaymentCommandHandlerTests.cs
- tests/VirtoCommerce.ExperienceApiModule.XOrder.Tests/Helpers/CustomerOrderMockHelper.cs
- tests/VirtoCommerce.ExperienceApiModule.XOrder.Tests/Helpers/Stubs/StubPaymentMethod.cs
- tests/VirtoCommerce.ExperienceApiModule.XOrder.Tests/VirtoCommerce.ExperienceApiModule.XOrder.Tests.csproj
```js
mutation addOrUpdateOrderPayment($command: InputAddOrUpdateOrderPaymentType!) {
addOrUpdateOrderPayment(command: $command) {
id
inPayments {
id
createdDate
billingAddress {
id
city
countryCode
countryName
email
firstName
lastName
line1
line2
middleName
name
organization
phone
postalCode
regionId
regionName
zip
addressType
}
paymentMethod {
code
paymentMethodType
paymentMethodGroupType
}
}
}
}
```
---
```json
{
"command": {
"orderId": "74d8b492-0bb5-486e-a0e6-0915848a7379",
"payment": {
"id": "123",
"paymentGatewayCode": "AuthorizeNetPaymentMethod",          
"billingAddress": {
"city": "Test",
"countryCode": "US",
"countryName": "US",
"email": "address@mail.test",
"firstName": "First test name",
"id": "KeyTest",
"key": "KeyTest",
"lastName": "Last name test",
"line1": "Address Line …
```
> PT-7938: add addOrUpdateOrderPayment mutation

- src/XPurchase/VirtoCommerce.XPurchase/Schemas/CartType.cs
https://virtocommerce.atlassian.net/browse/PT-7581
> PT-7581: Output field Subtotal discount

- docs/x-catalog-reference.md
Partly edited content. More reviews will be required moving forward.
> docs: Fix language - partly done

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchCategoryQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/CategoryType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/DigitalCatalogSchema.cs
https://virtocommerce.atlassian.net/browse/PT-8099
> PT-8099: Fix parent category response

- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Helpers/XPurchaseMoqHelper.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Validators/NewCartItemValidatorTests.cs
Modified tests for NewCartItemValidator using "strict" ruleset:
* valid;
* no inventory
* price error
https://virtocommerce.atlassian.net/browse/PT-5433 https://virtocommerce.atlassian.net/browse/PT-5435
> Modified tests for NewCartItemValidator using "strict" ruleset

- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/DynamicPropertyType.cs
https://virtocommerce.atlassian.net/browse/PT-4409
> PT-4409 Some dynamic property value can't be nullable

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/OutlineExtensions.cs
https://virtocommerce.atlassian.net/browse/PT-2323
> Adding the StoreId Condition to the Title Search

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/CreateOrderFromCartCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Repositories/CartAggregateRepositoryTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Validators/CartLineItemValidatorTests.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateRepository.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/CartType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartLineItemPriceChangedValidationContext.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartLineItemPriceChangedValidator.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartLineItemValidator.cs
- tests/VirtoCommerce.ExperienceApiModule.XOrder.Tests/Handlers/CreateOrderFromCartCommandHandlerTests.cs
- tests/VirtoCommerce.ExperienceApiModule.XOrder.Tests/Helpers/CustomerOrderMockHelper.cs
https://virtocommerce.atlassian.net/browse/PT-8113
> PT-8113: show actual product price in Cart lineitem

- src/XPurchase/VirtoCommerce.XPurchase/Authorization/CanAccessCartAuthorizationRequirement .cs
User1 without contact has access to user2's cart
https://virtocommerce.atlassian.net/browse/PT-7131
> Fix User1 without contact has access to user2's cart

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Authorization/CanAccessOrderAuthorizationHandler.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderSchema.cs
Before creating an order, user access is checked
https://virtocommerce.atlassian.net/browse/PT-8200
> PT-8200: Adding an access request when a user creates an order

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/DescriptionType.cs
https://virtocommerce.atlassian.net/browse/PT-6794
> PT-6794 Make DescriptionType fields nullable

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
https://virtocommerce.atlassian.net/browse/PT-8207
> PT-8207 Incorrect price display multiple prices (min. qty)

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddWishlistItemCommandHandler.cs
Validation fix when adding a product to the wishlist
https://virtocommerce.atlassian.net/browse/PT-8721
> PT-8721: Validation fix when adding a product to the wishlist

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/ExpProduct.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsPricesMiddleware.cs
Fix actual and discount for list and sales price and if no active marketing promo.
https://virtocommerce.atlassian.net/browse/PT-9020
> PT-9020: Fix Static Discounts if no active marketing promo

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/ExpVendorType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/GetVendorQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/GetVendorQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/VariationType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/VendorType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
https://virtocommerce.atlassian.net/browse/VM-869
> VM-869: Display vendor name

- src/VirtoCommerce.ExperienceApiModule.Core/Models/ProductPrice.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Models/TierPrice.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Mapping/ProductMappingProfile.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartProduct.cs
fix: list price is missing in the shopping cart
https://virtocommerce.atlassian.net/browse/PT-9020
> PT-9020: list price is missing in the shopping cart

- .gitignore
- .nuke
- VirtoCommerce.ExperienceApiModule.sln
- VirtoCommerce.ExperienceApiModule.sln.DotSettings
- module.ignore
- samples/VirtoCommerce.Exp.ExtensionSamples/VirtoCommerce.Exp.ExtensionSamples.csproj
- src/VirtoCommerce.ExperienceApiModule.Core/BaseQueries/CommandBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.Core/BaseQueries/Query.cs
- src/VirtoCommerce.ExperienceApiModule.Core/BaseQueries/QueryBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.Core/BaseQueries/RequestBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.Core/BaseQueries/SearchQuery.cs
- src/VirtoCommerce.ExperienceApiModule.Core/BaseQueries/SearchQueryBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ObjectExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/IHasArguments.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/ISearchQuery.cs
- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
- tests/VirtoCommerce.XDigitalCatalog.Tests/Handlers/SearchProductQueryHandlerTests.cs
https://virtocommerce.atlassian.net/browse/PT-8957
> PT-8957: Add common classes and extension methods for GraphQL requests

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderSchema.cs
fix: Improve error message if a cart is null
https://virtocommerce.atlassian.net/browse/PT-9034
> PT-9034: Improve error message if cart is null

- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartLineItemPriceChangedValidator.cs
fix: validation error when creating an order with product with list/sale price
https://virtocommerce.atlassian.net/browse/PT-9210
> PT-9210:Fix error when creating an order with product with list/sale price

- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Services/CartProductServiceFake.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Services/CartProductServiceTests.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/LineItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Services/CartProductService.cs
https://virtocommerce.atlassian.net/browse/PT-9138
> PT-9138: pass price eval context through middleware

- src/VirtoCommerce.ExperienceApiModule.Core/Helpers/Constants.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/Authorization/ForbiddenError.cs
Add ForbiddenError to enable different code for permission violation
https://virtocommerce.atlassian.net/browse/PT-9363
> PT-9363: Add ForbiddenError

- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Data/RecommendationsGatewayModule.Data.csproj
- samples/VirtoCommerce.Exp.ExtensionSamples/VirtoCommerce.Exp.ExtensionSamples.csproj
- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/Extensions/HttpContextExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
ME query
```
query {
me {
isAdministrator
id
email
contact {
name
}
operator {
userName
contact {
name
}
}
}
}
```
request example 
```
{
"Authorization": "Bearer <admin token here>",
"VirtoCommerce-User-Name": "<impersonated user name>",
"VirtoCommerce-Operator-User-Name": "<login on behalf operator user name>"
}
```
https://virtocommerce.atlassian.net/browse/PT-9274
> PT-9274: read VirtoCommerce-Operator-User-Name header to User Context

- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Validators/NewCartItemValidatorTests.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartErrorDescriber.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddCartItemsBulkCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/NewCartItemValidator.cs
Error codes:
* sku not found - CART_INVALID_PRODUCT 
* requested sku qty is more than available in FFC - PRODUCT_FFC_QTY
* sku Can be purchased=false - CART_PRODUCT_UNAVAILABLE
* sku Visible=false - CART_PRODUCT_INACTIVE
* sku Price=0 - PRODUCT_PRICE_INVALID
* requested sku qty is less than Min qty - PRODUCT_MIN_QTY
* requested sku qty is greater than Max qty	- PRODUCT_MAX_QTY
https://virtocommerce.atlassian.net/browse/PT-9106
> PT-9106: changed NewCartItem valitiator

- src/XPurchase/VirtoCommerce.XPurchase/Commands/CartCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/CreateCartCommandHandler.cs
https://virtocommerce.atlassian.net/browse/PT-9548
> PT-9548: Set organizationId in cart

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Binding/CatalogProductBinder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexFieldsMapper.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Services/CartProductServiceFake.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Services/CartProductServiceTests.cs
- src/XPurchase/VirtoCommerce.XPurchase/Services/CartProductService.cs
https://virtocommerce.atlassian.net/browse/PT-9602
https://virtocommerce.atlassian.net/browse/PT-9608
> PT-9602, PT-9608: Database Less Catalog: catalog browsing, cart operations

- VirtoCommerce.ExperienceApiModule.sln.DotSettings
- samples/VirtoCommerce.Exp.ExtensionSamples/VirtoCommerce.Exp.ExtensionSamples.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/ExpProduct.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/ExpProductResponseGroup.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsWishlistsMiddleware.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/VirtoCommerce.XPurchase.Tests.csproj
- src/XPurchase/VirtoCommerce.XPurchase/Mapping/CartMappingProfile.cs
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
https://virtocommerce.atlassian.net/browse/PT-9697
> PT-9697: Extend product with wishlist flag

- VirtoCommerce.ExperienceApiModule.sln.DotSettings
- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Core/RecommendationsGatewayModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/ExpCategory.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/CatalogQueryBase.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/CatalogQueryBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/ChildCategoriesQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/ChildCategoriesQueryBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/ChildCategoriesQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/ChildCategoriesQueryResponse.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/ChildCategoriesQueryResponseType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/CategoryType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/DigitalCatalogSchema.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/VirtoCommerce.ExperienceApiModule.Web.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- tests/VirtoCommerce.ExperienceApiModule.Tests/VirtoCommerce.ExperienceApiModule.Tests.csproj
```
query {
childCategories(
storeId: "test"
categoryId: null
maxLevel: 2
onlyActive: true
) {
childCategories {
id
name
childCategories {
id
name
}
}
}
}
```
https://virtocommerce.atlassian.net/browse/PT-9956
> PT-9956: Add ChildCategories query

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderShippingMethodType.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartProduct.cs
- src/XPurchase/VirtoCommerce.XPurchase/Services/CartProductService.cs
https://virtocommerce.atlassian.net/browse/PT-9602
> Bug fix with  inability to add database-less product to the cart

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/InputOrderShippingMethodType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderShippingMethodType.cs
https://virtocommerce.atlassian.net/browse/PT-10229
> PT-10229: make LogoUrl nullable for order shipping types

- samples/VirtoCommerce.Exp.ExtensionSamples/VirtoCommerce.Exp.ExtensionSamples.csproj
- src/VirtoCommerce.ExperienceApiModule.Core/ExpVendor.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/DataLoaderContextAccessorExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Mapping/CoreMappingProfile.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/VendorType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Models/ExpOrderPayment.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/InputOrderPaymentType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderShipmentType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/PaymentInType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/VirtoCommerce.XPurchase.Tests.csproj
- src/XPurchase/VirtoCommerce.XPurchase/ExpCartPayment.cs
- src/XPurchase/VirtoCommerce.XPurchase/ExpCartShipment.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputPaymentType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputShipmentType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PaymentType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/ShipmentType.cs
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
https://virtocommerce.atlassian.net/browse/PT-10134
> PT-10134: Add vendor in payment/shipment

- src/XPurchase/VirtoCommerce.XPurchase/Mapping/CartMappingProfile.cs
- src/XPurchase/VirtoCommerce.XPurchase/Services/CartProductService.cs
https://virtocommerce.atlassian.net/browse/PT-10315
> PT-10315: fix add to cart error

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexFieldsMapper.cs
https://virtocommerce.atlassian.net/browse/PT-10120
> PT-10120: load property display names from product document index

- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Data/RecommendationsGatewayModule.Data.csproj
- samples/VirtoCommerce.Exp.ExtensionSamples/VirtoCommerce.Exp.ExtensionSamples.csproj
- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderLineItemType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/VirtoCommerce.XPurchase.Tests.csproj
- src/XPurchase/VirtoCommerce.XPurchase/Mapping/CartMappingProfile.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/LineItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
https://virtocommerce.atlassian.net/browse/PT-10299
> PT-10299: add vendor to order line item type

- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Core/Schemas/ProductRecommendationType.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/AstFieldExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/CatalogQueryBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/CategoryType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/DigitalCatalogSchema.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductAssociationType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderLineItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/GiftItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/LineItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
Check include fields with directives @skip and @include.
Subfields are included in the context.SubFields.Values.GetAllNodesPaths result depending on the directives.
> Check include fields with directives

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsInventoryMiddleware.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsWishlistsMiddleware.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQueryHandler.cs
feat: Improve performance of EvalProductsInventoryMiddleware
https://virtocommerce.atlassian.net/browse/PT-10758
> PT-10758: Improve performance of EvalProductsInventoryMiddleware

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexFieldsMapper.cs
https://virtocommerce.atlassian.net/browse/PT-10616
> PT-10616: fix null product vendor

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/AstFieldExtensions.cs
https://virtocommerce.atlassian.net/browse/PT-10888
> PT-10888: Fix breaking changes

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/ExpProduct.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Mapping/ProductMappingProfile.cs
https://virtocommerce.atlassian.net/browse/PT-11091
> PT-11091: Fix discount amount for tier prices

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsDiscountsMiddleware.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/LoadProductsQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQuery.cs
- src/XPurchase/VirtoCommerce.XPurchase/Services/CartProductService.cs
https://virtocommerce.atlassian.net/browse/PT-11098
> PT-11098: Don't apply product promotions twice

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/CategoryDescriptionType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/CategoryType.cs
> feat: make CategoryDescriptionType public, virtual method

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexSearchRequestBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalSearchRequestUserGroupsMiddleware.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQueryHandler.cs
https://virtocommerce.atlassian.net/browse/PT-11213
> PT-11213: add product personalization

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/ExpProductResponseGroup.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/PropertyExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexFieldsMapper.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EnsurePropertyMetadataLoadedMiddleware.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/PropertyType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- tests/VirtoCommerce.XDigitalCatalog.Tests/Schemas/PropertyTypeTests.cs
https://virtocommerce.atlassian.net/browse/PT-11291
> PT-11291: load product property attributes via service

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderLineItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/GiftItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Services/CartProductService.cs
> pass userId for all cart's get products queries

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/VariationType.cs
fix: Add ProductType to Variation Schema.
https://virtocommerce.atlassian.net/browse/PT-11772
> PT-11772: Add ProductType to Variation Schema

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/CurrencyExtensions.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateRepository.cs
https://virtocommerce.atlassian.net/browse/PT-11112
> PT-11112: fix currency symbol in Wishlists

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
https://virtocommerce.atlassian.net/browse/PT-11728
> PT-11728: fix error trying to resolve empty 'images', 'assets'

- src/XPurchase/VirtoCommerce.XPurchase/Queries/GetWishlistQuery.cs
- src/XPurchase/VirtoCommerce.XPurchase/Queries/GetWishlistQueryHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
https://virtocommerce.atlassian.net/browse/PT-11641
> PT-11641: add cultureName to wishlist query

- samples/VirtoCommerce.Exp.ExtensionSamples/VirtoCommerce.Exp.ExtensionSamples.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.XPurchase/Mapping/CartMappingProfile.cs
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
https://virtocommerce.atlassian.net/browse/PT-11187
> PT-11187: update Marketing module (personal coupons)

- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Menu.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/MenuItem.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetMenuQuery.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetMenuQueryHandler.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetMenuResponse.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetMenusQueryHandler.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetMenusResponse.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Schemas/ContentSchema.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Schemas/MenuLinkListType.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Schemas/MenuLinkType.cs
https://virtocommerce.atlassian.net/browse/PT-11645
> PT-11645: Add get menu query

- samples/VirtoCommerce.Exp.ExtensionSamples/VirtoCommerce.Exp.ExtensionSamples.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Models/ExpOrderPayment.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/InputOrderPaymentType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/VirtoCommerce.XPurchase.Tests.csproj
- src/XPurchase/VirtoCommerce.XPurchase/ExpCartPayment.cs
- src/XPurchase/VirtoCommerce.XPurchase/ExpCartShipment.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputPaymentType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputShipmentType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PaymentType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/ShipmentType.cs
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
Use new cart properties in XPurchase
> Use comment from cart shipments and payments

- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartLineItemPriceChangedValidator.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartLineItemValidator.cs
https://virtocommerce.atlassian.net/browse/PT-11701
> PT-11701: fix NRE on product price deletion

- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/PageItem.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetPageQuery.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetPageQueryHandler.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetPageResponse.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Schemas/ContentSchema.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Schemas/PageType.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/VirtoCommerce.ExperienceApiModule.XCMS.csproj
https://virtocommerce.atlassian.net/browse/PT-10871
> add possibility to search static pages

- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Data/RecommendationsGatewayModule.Data.csproj
- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
> fix: update app insights package

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/PropertyExtensions.cs
https://virtocommerce.atlassian.net/browse/PT-11687
> PT-11687: filter out hidden properties

- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderLineItemType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
- tests/VirtoCommerce.ExperienceApiModule.XOrder.Tests/Helpers/CustomerOrderMockHelper.cs
https://virtocommerce.atlassian.net/browse/PT-11779
> PT-11779: add Status to OrderLineItemType

- src/XPurchase/VirtoCommerce.XPurchase/Commands/MergeCartCommandHandler.cs
fix: User can merge carts with the same id
https://virtocommerce.atlassian.net/browse/PT-12130
> PT-12130: User can merge carts with the same id

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/ProductSuggestionsQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/ProductSuggestionsQueryBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/ProductSuggestionsQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/ProductSuggestionsQueryResponse.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/ProductSuggestionsQueryResponseType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
```graphql
query {
productSuggestions(
query: "pr"
fields: ["name", "code"]
size: 10
) {
suggestions
}
}
```
https://virtocommerce.atlassian.net/browse/PT-11848
https://virtocommerce.atlassian.net/browse/PT-11854
> PT-11854: Add product suggestions

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/DataLoaderContextAccessorExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/CategoryType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderLineItemType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderShipmentType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/PaymentInType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/LineItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PaymentType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/ShipmentType.cs
https://virtocommerce.atlassian.net/browse/PT-11261
> PT-11261: return DataLoaderResult instead of null

- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/ProductSuggestionsQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/ProductSuggestionsQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
Removed Fields from suggestionsQuery
https://virtocommerce.atlassian.net/browse/PT-11860
> PT-11860: remove field from productSuggestions query

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexSearchRequestBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalSearchRequestUserGroupsMiddleware.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/ChildCategoriesQueryHandler.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/AuthorizePaymentCommandHandler.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/InitializePaymentCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartProduct.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeCartItemCommentCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Services/CartProductService.cs
https://virtocommerce.atlassian.net/browse/PT-12349
> PT-12349: convert 'price' filter to use currency

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsPricesMiddleware.cs
https://virtocommerce.atlassian.net/browse/PT-12319
> PT-12319: set current date for pricelist assignment evaluation

- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddOrUpdateCartAddressCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddOrUpdateCartPaymentCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddOrUpdateCartShipmentCommandHandler.cs
https://virtocommerce.atlassian.net/browse/PT-12435
> PT-1243: reload cart aggregate after addOrUpdateCartShipmentCommand

- src/XPurchase/VirtoCommerce.XPurchase/Schemas/LineItemType.cs
https://virtocommerce.atlassian.net/browse/PT-12449
> PT-12449: pass store Id to 'product' cart line item field

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateRepository.cs
https://virtocommerce.atlassian.net/browse/PT-11914
> PT-11914: update cart organizationId

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RemoveCartItemsCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RemoveCartItemsCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputRemoveItemsType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
https://virtocommerce.atlassian.net/browse/PT-12690
> PT-12690: remove multiple items from cart

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Mapping/ProductMappingProfile.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/LoadCategoryQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchCategoryQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchCategoryQueryHandler.cs
https://virtocommerce.atlassian.net/browse/PT-11761
> PT-1176: load child categories in category query

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchCategoryQueryHandler.cs
https://virtocommerce.atlassian.net/browse/PT-1674
> PT-1674: hide inactive categories from search

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Binding/MinVariationPriceBinder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/ExpProduct.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/ExpProductResponseGroup.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexFieldsMapper.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsPricesMiddleware.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- tests/VirtoCommerce.XDigitalCatalog.Tests/Mappers/IndexFieldsMapperTests.cs
```js
{
products(storeId:"Electronics" productIds:["6e7a31c35c814fb389dc2574aa142b63"] currencyCode: "USD")
{
totalCount
items {
minVariationPrice {
actual {
amount
}
}
}
}
}
```
https://virtocommerce.atlassian.net/browse/PT-8313
> PT-8313: add product min variation price

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQuery.cs
fix: isBuyable and isAvailable return always false. if request a product without the price
https://virtocommerce.atlassian.net/browse/PT-12850
> PT-12850: isBuyable and isAvailable always return false. 

- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderShippingMethodType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/ShipmentType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/ShippingMethodType.cs
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
https://virtocommerce.atlassian.net/browse/PT-12787
> PT-12787: add shipping method type name and description

- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddWishlistBulkItemCommandHandler.cs
https://virtocommerce.atlassian.net/browse/PT-12751
> PT-12751: lower validation requirement for bulk wishlist operation

- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/Authorization/AuthorizationError.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Services/IUserManagerCore.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Services/UserManagerCore.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderSchema.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
https://virtocommerce.atlassian.net/browse/PT-12906
> PT-12906: add check for locked user in order/purchase schemas

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderShipmentItemType.cs
> PT-12804: Add status to order shipment line item

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Binding/MinVariationPriceBinder.cs
https://virtocommerce.atlassian.net/browse/PT-13052
> PT-13052: parse minVariationPrice from an array of strings

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartProduct.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddWishlistBulkItemCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddWishlistItemCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Mapping/CartMappingProfile.cs
- src/XPurchase/VirtoCommerce.XPurchase/NewCartItem.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/LineItemType.cs
https://virtocommerce.atlassian.net/browse/PT-12811
> PT-12811: set default price when adding null priced products to wishlist

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/ExpProduct.cs
https://virtocommerce.atlassian.net/browse/PT-13349
> PT-13349: fix incorrect line item FF center

- src/VirtoCommerce.ExperienceApiModule.Core/BaseQueries/RequestBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ResolveFieldContextExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Helpers/Constants.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/Authorization/AuthorizationError.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/Authorization/ForbiddenError.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Services/IUserManagerCore.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Services/UserManagerCore.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderSchema.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
feat: Returns correct authorization error codes
Code | Message | Recommended Action
-- | -- | --
Unauthorized | Anonymous access denied or access token has expired or is invalid. | Redirect to Signin page
Forbidden | Access denied. | Display Access Denied page
Forbidden | User doesn't have the required permission 'name'. | Display Access Denied page
UserLocked | This user is locked. | Display Error page
PasswordExpired | This user has their password expired. Please change the password using   'changePassword' command. | Open Change Password form
https://virtocommerce.atlassian.net/browse/PT-13290
> PT-13290: Use correct authorization error codes

- src/XPurchase/VirtoCommerce.XPurchase/CartErrorDescriber.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartValidator.cs
https://virtocommerce.atlassian.net/browse/PT-13685
> PT-13685: add before create order validation rule

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
https://virtocommerce.atlassian.net/browse/PT-13521
> PT-13521: filter out inactive variations in ProductType.Variatons

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/SeoInfosExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ServiceCollectionExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/SlugInfoQuery.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/SlugInfoQueryBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/SlugInfoQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/SlugInfoResponse.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/SlugInfoResponseType.cs
- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
```
{
slugInfo(storeId:"B2B-store"
cultureName:"en-US"
slug: "bolts/carriage-bolts/1-steel-carriage-bolt-grade-5-chrome-plated-finish-14-20-diathread-size-5-pk"
)
{
entityInfo {
id
objectId
objectType
}
}
}
```
https://virtocommerce.atlassian.net/browse/PT-13454
> PT-13454: add slugInfo query

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/CreateOrderFromCartCommandHandler.cs
https://virtocommerce.atlassian.net/browse/PT-13692
> PT-13692: clear payments and shipments after order create

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/Services/CartAvailMethodsService.cs
- Fix nullable bool compare, because a value of type 'bool' is never equal to 'null' of type 'bool?'
> Fix nullable bool compare

- src/VirtoCommerce.ExperienceApiModule.Web/Localizations/en.VirtoCommerce.ExperienceApi.json
- src/VirtoCommerce.ExperienceApiModule.Web/Module.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderSchema.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/XOrderConstants.cs
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
https://virtocommerce.atlassian.net/browse/PT-13757
> PT-13757: check anonymous access before order create by store setting

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/TransferOrderCommand.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/TransferOrderCommandHandler.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/CustomerOrderAggregate.cs
https://virtocommerce.atlassian.net/browse/PT-13765
> PT-13765: add Transfer Order command

- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/TransferOrderCommandHandler.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/CustomerOrderAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
https://virtocommerce.atlassian.net/browse/PT-13935
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.425.0-pr-470-5dcc.zip
> PT-13935: transfer only IsAnonymous order

- src/XPurchase/VirtoCommerce.XPurchase/CartErrorDescriber.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/NewCartItemValidator.cs
https://virtocommerce.atlassian.net/browse/PT-13946
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.427.0-pr-475-a264.zip
> PT-13946: change product code to product id in NewCartItemValidator

- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/PageItem.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetPageQueryHandler.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Schemas/PageType.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/VirtoCommerce.ExperienceApiModule.XCMS.csproj
use updated content module for search
https://virtocommerce.atlassian.net/browse/PT-14120
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.427.0-pr-474-a593.zip
> PT-14120: use updated content module for search

- src/VirtoCommerce.ExperienceApiModule.Core/Queries/SlugInfoQueryHandler.cs
https://virtocommerce.atlassian.net/browse/PT-13744
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.428.0-pr-477-0c5c.zip
> PT-13744: filter results by storeid

- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS.Tests/Handlers/GetMenusQueryHandlerTests.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetMenuQueryHandler.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetMenusQueryHandler.cs
https://virtocommerce.atlassian.net/browse/PT-14420
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.429.0-pr-478-a20b.zip
> PT-14420: Fix Obsolete warnings and dependency

- src/XPurchase/VirtoCommerce.XPurchase/Authorization/CanAccessCartAuthorizationRequirement .cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeWishlistCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeWishlistCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputChangeWishlistType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
```js
mutation changeWishlist ($command: InputChangeWishlistType!) {
changeWishlist (command: $command) {
id
name
name
scope
description
}
}
```
---
```json
{
"command": {
"listId": "4c9fac2c-cdbe-410d-be85-8e69b76c50e2",
"listName": "new list name",
"scope": "private",
"description": "new description"
}
}
```
> PT-14401: add changeWishlist mutation

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderShipmentType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/ShipmentType.cs
- Add Fee and FeeWithTax properties to ShipmentType
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.431.0-pr-486-8ced.zip
> feat: Add Fee and FeeWithTax properties to ShipmentType

- src/XPurchase/VirtoCommerce.XPurchase/ExpCartAddress.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/CartAddressType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputAddressType.cs
- feat: Add description property to XAPI address
https://virtocommerce.atlassian.net/browse/PT-14271
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.432.0-pr-485-0cee.zip
> feat: Add description property to XAPI address

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/CustomerOrderType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/CartType.cs
- Add Fee properties to CartType and CustomerOrderType
- Change ShipmentPrice and PaymentPrice source
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.432.0-pr-488-a77f.zip
> feat: Add Fee properties to CartType and CustomerOrderType, change ShipmentPrice and PaymentPrice source

- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.XPurchase/Authorization/CanAccessCartAuthorizationRequirement .cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartSearchCriteriaBuilder.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddWishlistItemsCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/AddWishlistItemsCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeWishlistCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeWishlistCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/CreateWishlistCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/CreateWishlistCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/WishlistCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/WishlistUserContext.cs
- src/XPurchase/VirtoCommerce.XPurchase/Queries/SearchWishlistQueryHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputAddWishlistItemsType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputChangeWishlistType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputCreateWishlistType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputNewWishlistItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/WishlistScopeType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/WishlistType.cs
- src/XPurchase/VirtoCommerce.XPurchase/XPurchaseConstants.cs
```js
mutation createWishlist ($command: InputCreateWishlistType!) {
createWishlist (command: $command) {
id
name
storeId
scope
description
}
}
```
```json
{
"command": {
"storeId": "Electronics",
"userId": "530dbc7b-796a-4eea-bca5-10568b3c5050",
"listName": "some name",
"cultureName": "en-US",
"currencyCode": "USD",
"scope": "organization",
"description": "some description"
}
}
```
---
```js
mutation changeWishlist ($command: InputChangeWishlistType!) {
changeWishlist (command: $command) {
id
name
name
scope
description
}
}
```
```json
{
"command": {
"listId": "4c9fac2c-cdbe-410d-be85-8e69b76c50e2",
"listName": "new list name",
"scope": "private",
"description": "new description"
}
}
```
---
```js
mutation addWishlistItems($command: InputAddWishlistItemsType!) {
addWishlistItems(command: …
```
> PT-14414: add Wishlist scopes, changeWishlish, addWishlistItems mutations

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
feat: ClearCart mutation should clear: line-items, comments, coupons, purchase order number, shipments, payments and addresses.
https://virtocommerce.atlassian.net/browse/PT-14374
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.436.0-pr-491-9614.zip
> PT-14374: ClearCart should clear all items from cart

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Authorization/CanAccessOrderAuthorizationHandler.cs
fix: Allows anonymous user access to anonymous order and complete payment
https://virtocommerce.atlassian.net/browse/PT-14746
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.440.0-pr-495-1777.zip
> PT-14746: Allows anonymous user access to anonymous order

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateRepository.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/WishlistType.cs
https://virtocommerce.atlassian.net/browse/PT-14762
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.441.0-pr-497-7334.zip
> PT-14762: add ModifiedDate field to WishlistType

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.XPurchase/CartSearchCriteriaBuilder.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeWishlistCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Queries/SearchWishlistQuery.cs
- src/XPurchase/VirtoCommerce.XPurchase/Queries/SearchWishlistQueryHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
```js
query {
wishlists(
userId:"07be1210-a740-49b0-98f0-7afa6e807d45"
#scope: "Organization"
scope: "Private"
) {
totalCount
items {
description
scope
name
id
}
}
}
```
https://virtocommerce.atlassian.net/browse/PT-14606
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.443.0-pr-496-3cbd.zip
> PT-14606: add Scope to Wishlists query arguments

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/AstFieldExtensions.cs
https://virtocommerce.atlassian.net/browse/PT-14668
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.445.0-pr-501-72ad.zip
> PT-14668: add fragments support to IncludeFields list

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Aggregates/CartAggregateTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Handlers/AddCartItemsCommandHandlerTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Handlers/CreateOrderFromCartCommandHandlerTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Helpers/XPurchaseMoqHelper.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Repositories/CartAggregateRepositoryTests.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateRepository.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/CartCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/CartType.cs
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
- tests/VirtoCommerce.ExperienceApiModule.XOrder.Tests/Handlers/CreateOrderFromCartCommandHandlerTests.cs
fix: Organization Name is empty
https://virtocommerce.atlassian.net/browse/PT-14655
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.445.0-pr-502-575a.zip
> PT-14655: Organization Name is empty

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
Save discount for gift item in order
https://virtocommerce.atlassian.net/browse/PT-14577
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.447.0-pr-505-c1ac.zip
> PT-14577: log gift promotion

- VirtoCommerce.ExperienceApiModule.sln.DotSettings
- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/GraphQLBuilderExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/Validation/CustomFieldsOnCorrectType.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/Validation/CustomKnownArgumentNames.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/Validation/CustomKnownTypeNames.cs
- src/VirtoCommerce.ExperienceApiModule.Web/Module.cs
https://virtocommerce.atlassian.net/browse/PT-14894
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.447.0-pr-506-b3a7.zip
> PT-14894: Don't use 'await' with Task.FromResult(). Refactoring.

- src/XPurchase/VirtoCommerce.XPurchase/Commands/RemoveWishlistItemsCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RemoveWishlistItemsCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputRemoveWishlistItemsType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
```js
mutation removeWishlistItems ($command: InputRemoveWishlistItemsType!) {
removeWishlistItems (command: $command) {
id
items {
id
sku
quantity
}
}
}
```
```json
{
"command": {
"listId": "300f32d8-605e-4260-ba73-8f3fb8af319b",
"lineItemIds": ["8386c9f5-a3de-4163-93da-6ee4e497796c"]
}
}
```
https://virtocommerce.atlassian.net/browse/PT-14350
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.449.0-pr-509-4228.zip
> PT-14350: add removeWishlistItems mutation

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/PropertyType.cs
https://virtocommerce.atlassian.net/browse/PT-14777
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.449.0-pr-510-8a19.zip
> PT-14777: return fake Id for Product Properties with NULL Ids

- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
https://virtocommerce.atlassian.net/browse/PT-14977
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.449.0-pr-508-1043.zip
> PT-14977: fix NRE when updating cart dynamic properties

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/NewCartItemValidator.cs
https://virtocommerce.atlassian.net/browse/PT-14900
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.449.0-pr-504-981c.zip
> PT-14900: add cart validation error on invalid product add

- Directory.Build.props
- samples/PetsStoreClient/PetsStoreClient.csproj
- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Core/RecommendationsGatewayModule.Core.csproj
- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Data/LiquidContentRenderer.cs
- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Data/RecommendationsGatewayModule.Data.csproj
- samples/RecommendationsGatewayModule/RecommendationsGatewayModule.Web/RecommendationsGatewayModule.Web.csproj
- samples/VCCatalogClient/VCCatalogClient.csproj
- samples/VirtoCommerce.Exp.ExtensionSamples/VirtoCommerce.Exp.ExtensionSamples.csproj
- src/VirtoCommerce.ExperienceApiModule.Core/Services/DynamicPropertyUpdaterService.cs
- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Mapping/FacetMappingProfile.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchPropertyDictionaryItemQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/VirtoCommerce.ExperienceApiModule.Web.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS.Tests/VirtoCommerce.ExperienceApiModule.XCMS.Tests.csproj
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/VirtoCommerce.ExperienceApiModule.XCMS.csproj
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Aggregates/CartAggregateTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/VirtoCommerce.XPurchase.Tests.csproj
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
- tests/VirtoCommerce.ExperienceApiModule.Tests/Services/DynamicPropertyUpdaterServiceTests.cs
- tests/VirtoCommerce.ExperienceApiModule.Tests/VirtoCommerce.ExperienceApiModule.Tests.csproj
- tests/VirtoCommerce.ExperienceApiModule.XOrder.Tests/MappingTermFilterTests.cs
- tests/VirtoCommerce.ExperienceApiModule.XOrder.Tests/VirtoCommerce.ExperienceApiModule.XOrder.Tests.csproj
- tests/VirtoCommerce.XDigitalCatalog.Tests/VirtoCommerce.XDigitalCatalog.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/RecommendationsGatewayModule.Web-sample-VirtoCommerce.ExperienceApiModule.3.800.0-pr-499-b6bf.zip
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.800.0-pr-499-b0fa.zip
> PT-14740: update to .NET8

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
https://virtocommerce.atlassian.net/browse/VCST-157
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.450.0-pr-512-51b2.zip
> VCST-157: support multiple rules in ruleSet

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsWishlistsMiddleware.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
https://virtocommerce.atlassian.net/browse/VCST-6
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.804.0-pr-524-a591.zip
> VCST-6: resolve InWishlists field for organization scoped lists

- src/VirtoCommerce.ExperienceApiModule.Web/Extensions/HttpContextExtensions.cs
fix: An issue was identified where the anonymous cart was being reset upon browser refresh. Virto Storefront, Virto Commerce Experience and Profile Experience module should be updated as well.
https://virtocommerce.atlassian.net/browse/VCST-192
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.806.0-pr-526-154b.zip
> VCST-192: Anonymous Cart Reset Issue Upon Browser Refresh

- src/XPurchase/VirtoCommerce.XPurchase/Authorization/CanAccessCartAuthorizationRequirement .cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/CreateWishlistCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RemoveWishlistCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RemoveWishlistCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/WishlistUserContext.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
Extend WishlistUserContext and extend authorize by wishlist command and query
These changes are necessary so that wishlists authorization can be checked separately for commands and for query.
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.807.0-pr-525-b4e0.zip
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.807.0-pr-525-42f1.zip
> feat: Extend WishlistUserContext and authorize by wishlist command

- src/XPurchase/VirtoCommerce.XPurchase/Schemas/LineItemType.cs
https://virtocommerce.atlassian.net/browse/VCST-378
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.809.0-pr-532-6d2e.zip
> VCST-378: fix culture name not being passed in cart mutations

- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
https://virtocommerce.atlassian.net/browse/VCST-480
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.809.0-pr-531-7771.zip
> VCST-480: restrict clone wishlist with another userId

- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeWishlistCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputChangeWishlistType.cs
```
{
"command": {
"listId": "dfe48e51-6212-4b4f-b501-a5f2e48459e3",
"listName": "name2",
"scope": "organization",
"description": "descr2",
"cultureName": "en-US"
}
}
```
https://virtocommerce.atlassian.net/browse/VCST-377
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.810.0-pr-529-e645.zip
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.808.0-pr-529-f277.zip
> VCST-377: add cultureName to ChangeWishlist mutation

- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/SubscriptionSchema.cs
https://virtocommerce.atlassian.net/browse/VCST-872
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.817.0-pr-542-2382.zip
> VCST-872: add non-functional subscription

- Directory.Build.props
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/ExpProduct.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsWishlistsMiddleware.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RemoveWishlistItemCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RemoveWishlistItemCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/CartType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputRemoveWishlistItemType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/WishlistType.cs
https://virtocommerce.atlassian.net/browse/VCST-533
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.818.0-pr-540-caca.zip
> VCST-533: improve wishlist performance

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexFieldsMapper.cs
https://virtocommerce.atlassian.net/browse/VCST-776
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.819.0-pr-541-6dbc.zip
> VCST-776: fix: Incorrect availability data when storing catalog objects in index

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateRepository.cs
This PR will make the SaveAsync method in the CartAggregateRepository virtual, therefore ensuring it can be overridden,
> Add the virtual keyword to CartAggregateRepository.SaveAsync

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/SeoInfosExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/SlugInfoQueryHandler.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetPageQueryHandler.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/VirtoCommerce.ExperienceApiModule.XCMS.csproj
- tests/VirtoCommerce.ExperienceApiModule.Tests/Extensions/SeoInfosExtensionsTests.cs
https://virtocommerce.atlassian.net/browse/VCST-690
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.829.0-pr-554-e615.zip
> VCST-690: use scores to range pages

- src/VirtoCommerce.ExperienceApiModule.Core/ModuleConstants.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/GetStoreQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/StoreSettings.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/StoreSettingsType.cs
- src/VirtoCommerce.ExperienceApiModule.Web/Localizations/en.VirtoCommerce.ExperienceApi.json
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/CreateOrderFromCartCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/Extensions/RewardExtensions.cs
- src/XPurchase/VirtoCommerce.XPurchase/GiftItem.cs
- src/XPurchase/VirtoCommerce.XPurchase/Mapping/CartMappingProfile.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/CartType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Services/CartAvailMethodsService.cs
**Default: true**
https://virtocommerce.atlassian.net/browse/VCST-1158
https://virtocommerce.atlassian.net/browse/VCST-1157
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.831.0-pr-553-fead.zip
> VCST-1158, VCST-1157: add Selected for checkout setting

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/CustomerOrderAggregateRepository.cs
https://virtocommerce.atlassian.net/browse/VCST-1266
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.829.0-pr-555-a9e1.zip
> VCST-1266: Do not load the order after creating it from the cart

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ResolveFieldContextExtensions.cs
https://virtocommerce.atlassian.net/browse/VCST-1322
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.833.0-pr-557-3126.zip
> VCST-1322: add argument to user context only once

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/SeoInfosExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/SlugInfoQuery.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/SlugInfoQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetPageQueryHandler.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetSinglePageQueryHandler.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/VirtoCommerce.ExperienceApiModule.XCMS.csproj
https://virtocommerce.atlassian.net/browse/VCST-1363
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.834.0-pr-558-8097.zip
> VCST-1363: Seo Search  by permalink

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/ResolveFieldContextExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/ICatalogQuery.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeWishlistCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeWishlistCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/CloneWishlistCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/CloneWishlistCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/CreateWishlistCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/CreateWishlistCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ScopedWishlistCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ScopedWishlistCommandHandlerBase.cs
A wishlist becomes anonymous if the user who created it doesn't exist anymore. This can be fixed by separating wishlists from shopping carts.
https://virtocommerce.atlassian.net/browse/VCST-1416
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.839.0-pr-563-b7bf.zip
> VCST-1416: Fix setting a scope for a wishlist

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/ChildCategoriesQueryResponseType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/CategoryType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
Make object type fields extendable in:
- CategoryType
- ProductType
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.840.0-pr-564-e9f2.zip
> feat: Make object type fields extendable

- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Aggregates/CartAggregateTests.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
https://virtocommerce.atlassian.net/browse/VCST-1522
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.841.0-pr-566-68f9.zip
> VCST-1522: Don't merge shipments/payments if there are already shipments/payments in the cart

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/CreateOrderFromCartCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
https://virtocommerce.atlassian.net/browse/VCST-1562
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.842.0-pr-568-a1c7.zip
> VCST-1562: update organization name on order create

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
feat: Adds a new FindExistingLineItemBeforeAdd method. It is responsible for finding an existing line item before adding a new one. If the method returns the line item, the new line item should be merged with the existing one.
> VCST-1564: Adds FindExistingLineItemBeforeAdd method

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQueryHandler.cs
https://virtocommerce.atlassian.net/browse/VCST-1541
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.844.0-pr-570-16d5.zip
> VCST-1541: add default "product" filter to product search query

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateResponseGroup.cs
- src/XPurchase/VirtoCommerce.XPurchase/Services/CartResponseGroupParser.cs
fix: Empty totals if shipment is requested
https://virtocommerce.atlassian.net/browse/VCST-2173
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.846.0-pr-572-2d78.zip
> VCST-2173: Empty totals if shipment is requested
