- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/SearchRequestBuilder.cs
This is required for proper filters parsing - non escaped spaces break filter parsing
> VP-3940: Add escaped spaces support to filters

- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Aggregates/CartAggregateTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Helpers/XPurchaseMoqHelper.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateRepository.cs
- src/XPurchase/VirtoCommerce.XPurchase/ICartAggregateRepository.cs
https://virtocommerce.atlassian.net/browse/VP-4045
> VP-4045 Fix: recalucate aggregation after products loaded

- src/XPurchase/VirtoCommerce.XPurchase/Schemas/CartType.cs
fix empty cart.id after saving cart
Return cart.id if cartAggregate.id is null
> VP-3733: fix cache issue when user create wishlist

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartErrorDescriber.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartValidationError.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/ErrorParameter.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/ErrorParameterType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/ValidationErrorType.cs
Error when user add more products than contains in stock
Do not throw error when item quantity invalid
> VP-3968: Fix error when user add more products than contains in stock

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Binding/PriceBinder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Mapping/ProductMappingProfile.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsPricesMiddleware.cs
1. Pricing evaluation is not enough because of all calculations based on the current prices;
2. Binding was incorrect.
1. Move past the logic of getting prices from Indexed Prices;
2. Fix binder to not creating prices with 0 (zero) cost.
https://virtocommerce.atlassian.net/browse/VP-6197
> VP-6197: Fix prices entry mapping

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeCartItemPriceCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/ChangeCartItemPriceCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputChangeCartItemPriceType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
VP-6103 Create example queries for QA team
changeCartItemPrice. the field named as productId. When productId from platform set then nothing happens. When lineItemId set to productId from cart then price changed
Fix behaviour related to storefront
Linq query updated
> VP-6103: Fix changeLineItemPrise mutation

- src/VirtoCommerce.ExperienceApiModule.Web/Module.cs
VP-6356 Nullable DateTime field types for GraphQL schema do not return time in result
Map DateTime to DateTimeGraphType
> VP-6356: DateTime for GraphQL schema returns only date

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
1. It is possible to skip validation in the `addItem` mutation for "manual price".
2. No errors are shown in the response.
1. Do not clear errors after mutation;
2. Do not add an item to the cart if validation fails.
https://virtocommerce.atlassian.net/browse/VP-6425
> VP-6425: prevent buy less price

- README.md
- docs/index.md
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
VP-6269 [X-API] As a platform user, I want to be able to install and use XAPI module without ElasticSearch module installed 
Remove VirtoCommerce.ElasticSearch module dependency
Add module limitation to documentation
> VP-6269: Use xapi module without elastic search module

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/ResolveFieldContextExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/DigitalCatalogSchema.cs
VP-6701 [XAPI] Error in response if product does not have price
When product does not have price then error shown in response
"GraphQL.Execution.UnhandledError: Error trying to resolve field 'price'
C:\\Develop\\PlatformCoreModules\\vc-module-experience-api\\src\\VirtoCommerce.ExperienceApiModule.DigitalCatalog\\Schemas\\ProductType.cs:line 238"
https://github.com/VirtoCommerce/vc-module-experience-api/blob/3cf29f9ad090ea4e91860aeddbe7e9eceb78ca7a/src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs#L238
Make currencyCode filed NotNullGraphType for product query
> VP-6701: [XAPI] Error in response if product does not have price

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexFieldsMapper.cs
This change allows to IndexFieldsMapper work 2x+ faster.
Because:
1. Regexes precompiled;
2. Mappers cached in process with precompiled regexes;
3. List and List.Distinct avoided calling.
> VP-6875: Optimize IndexFieldsMapper

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/ConfirmOrCancelOrderPaymentCommandHandler.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/CustomerOrderAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Aggregates/CustomerOrderAggregateTests.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/VirtoCommerce.XPurchase.Tests.csproj
https://virtocommerce.atlassian.net/browse/VP-6263 The payment status remains the same after cancelled
https://virtocommerce.atlassian.net/browse/VP-6264 Confirm payment request can create separate payment document
Fix the issue with setting any payment status when calling confirmOrderPayment or cancelOrderPayment
Fix issue with new payment creation when calling confirmOrderPayment or cancelOrderPayment
Add tests
> VP-6264: Fix confirm payment request can create separate payment document

- src/VirtoCommerce.ExperienceApiModule.Core/Services/DynamicPropertyUpdaterService.cs
The reason is to emulate non-null locale to correctly use in compare in case of null dynamic property value locale
https://virtocommerce.atlassian.net/browse/PT-2808
> PT-2810: Eliminate call Equals for null locales

- .github/workflows/integration-tests.yml
https://virtocommerce.atlassian.net/browse/PT-2916
- Integration-tests workflow synchronized with e2e platform workflow.
- run-on workflow environment set to ubuntu-18.04 due to katalon action don`t run correctly on ubuntu-20.04 environment
- changed Katalon Studio Github Action to virtocommecrce fork 
- changed docker repository to ghcr.io
> PT-2916: # Fix Experience API Integration tests not working

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/CategoryType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
Added possibility to filter products and categories properties by their names
https://virtocommerce.atlassian.net/browse/PT-4102
> PT-4102: filter product and category properties by their names

- src/XProfile/VirtoCommerce.XProfile/Commands/UpdateOrganizationCommand.cs
Currently it will remove dynamic properties values on updateOrganization call
> VDS-2855: Exclude dynamic properties from updateOrganization mutation command fields

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/CreateOrderFromCartCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Handlers/CreateOrderFromCartCommandHandlerTests.cs
Softly delete the cart after an order created based on
https://virtocommerce.atlassian.net/browse/PT-4621
> PT-4621: Softly delete the cart after an order created based on

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsPricesMiddleware.cs
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Services/CartProductServiceFake.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Services/CartProductServiceTests.cs
- src/XPurchase/VirtoCommerce.XPurchase/Services/CartProductService.cs
DL-60 inspired. Use IPricingEvaluatorService instead of obsolete and too complex IPricingService.
https://virtocommerce.atlassian.net/browse/DL-60
> DL-60: remove usage of obsolete IPricingService

- docs/x-purchase-order-reference.md
- src/VirtoCommerce.ExperienceApiModule.Core/Models/KeyValuePair.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/InputKeyValueType.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/KeyValueType.cs
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/AuthorizePaymentCommand.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/AuthorizePaymentCommandHandler.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/InitializePaymentCommand.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/InitializePaymentCommandHandler.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/PaymentCommandBase.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/PaymentCommandHandlerBase.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Models/AuthorizePaymentResult.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Models/InitializePaymentResult.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Models/PaymentInfo.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Models/PaymentResult.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/OrderErrorDescriber.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/AuthorizePaymentResultType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/InitializePaymentResultType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/InputAuthorizePaymentType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/InputInitializePaymentType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderPaymentMethodType.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderSchema.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Validators/PaymentRequestValidator.cs
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/VirtoCommerce.ExperienceApiModule.XOrder.csproj
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
```js
mutation {
initializePayment(command: {
orderId: "123",
paymentId: "345"
}) {
isSuccess
errorMessage
storeId
paymentId
orderId
orderNumber
paymentMethodCode
paymentActionType
actionRedirectUrl
actionHtmlForm
publicParameters {
key
value
}
}
}
```
--------------------
```js
mutation {
authorizePayment(command: {
orderId: "123",
paymentId: "345"
parameters: [
{ 
key: "dataValue", 
value: "123"
},
{ 
key: "dataDescriptor", 
value: "456" 
}
]
}) {
isSuccess
errorMessage
}
}
```
https://virtocommerce.atlassian.net/browse/PT-7542
> PT-7542, PT-7548: add initializePayment mutation, authorizePayment mutation

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/PropertyExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/StringExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/XDigitalCatalogConstants.cs
```js
query {
products(
storeId: "B2B-store"
cultureName: "en-US"
) {
items {
code
keyProperties (take:3) {
name
value
valueType
}
}
}
}
```
----
To use key propeties add `KeyProperty` attribute to property attributes. Value - int, ascending order.
https://virtocommerce.atlassian.net/browse/PT-8162
> PT-8162: add key property support

- src/XPurchase/VirtoCommerce.XPurchase/Authorization/CanAccessCartAuthorizationRequirement .cs
if searchQuery contains UserId = User_1:
1) User_1 : Access allowed for Cart_1
2) Anonymous : Access allowed for Cart_1
3) User_2: Access denied for Cart_1
if searchQuery does not contain UserId:
1) User_1 : Access allowed for Cart_1
2) Anonymous : Access denied for Cart_1
3) User_2: Access allowed for Cart_2
https://virtocommerce.atlassian.net/browse/PT-8543
> PT-8543 "Get all carts" request authorization rules failed (XAPI)

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/CategoryType.cs
fix: Argument Null Exception. Add null check if the Category object is null.
https://virtocommerce.atlassian.net/browse/PT-10279
> PT-10279: Argument Null Exception if Category object is null.

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/IFiltertExtensions.cs
- tests/VirtoCommerce.XDigitalCatalog.Tests/Extensions/IFilterExtensionTests.cs
fix: IFiltertExtensions.GetFieldName bug for __outiline field
https://virtocommerce.atlassian.net/browse/PT-10149
> PT-10149: IFiltertExtensions.GetFieldName bug for __outiline field

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/IFiltertExtensions.cs
- tests/VirtoCommerce.XDigitalCatalog.Tests/Extensions/IFilterExtensionTests.cs
fix: IsSelected always returns false for term with underscore in name, like LCD_Size.
https://virtocommerce.atlassian.net/browse/PT-9745
> PT-9745: isSelected always returns false for term with underscore in name, like LCD_Size

- src/XPurchase/VirtoCommerce.XPurchase/Services/CartProductService.cs
fix: wrong price in the cart if product has several price lists and store is muti-currency.
https://virtocommerce.atlassian.net/browse/PT-11736
> PT-11736: wrong price in the cart if product has several price lists

- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateRepository.cs
fix: Cart Language Code never changed after creation. After the fix, cart Cart Language Code is actualized from mutation context.
https://virtocommerce.atlassian.net/browse/PT-11539
> PT-11539: Cart Language Code never changed after creation

- .github/CODEOWNERS
- docs/x-purchase-cart-reference.md
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/CreateOrderFromCartCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Validators/CartLineItemValidatorTests.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregateRepository.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RefreshCartCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/RefreshCartCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/RefreshCartType.cs
- src/XPurchase/VirtoCommerce.XPurchase/Specifications/ProductIsBuyableSpecification.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartLineItemPriceChangedValidator.cs
- src/XPurchase/VirtoCommerce.XPurchase/Validators/CartLineItemValidator.cs
fix: The cart allows proceeding to checkout with a product with 0 price.
fix: Get cart query can leads to DbUpdateConcurrencyException.
fix: "Price was changed" cart warning treats as error on order creation.
feat: Added options for customization, ex: if you want to allow buying the product with Zero price, you should override ProductIsBuyableSpecification.CheckPricePolicy and CartAggregate.CheckPricePolicy.
https://virtocommerce.atlassian.net/browse/PT-12005
> PT-12005: The cart allows proceeding to checkout with a product with 0 price.

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalSearchRequestUserGroupsMiddleware.cs
fix: XAPI returns Zero Products if Catalog Personalization Module is not installed. With this fix, a check has been implemented to determine if the Catalog Personalization Module is installed. If it is installed, the fix adds user groups as a filter criterion when retrieving products through the XAPI. This ensures that the product response is accurate and includes only the relevant products based on the user's group affiliations.
https://virtocommerce.atlassian.net/browse/PT-11605
> PT-11605: XAPI returns Zero Products if Catalog Personalization Module is not installed.

- src/XPurchase/VirtoCommerce.XPurchase/Extensions/RewardExtensions.cs
fix: Cart Promo uses List price for CartSubtotalReward.
1. Create product with $100 list price and $50 sale price
2. Create promo 10% for subtotal
3. Add product to cart
4. Check totall
**Actual result**
Total $40
$50 - from sale price
$10  - from promo (10% from list prices)
**Expected result**
Total $45
$50 - from sale price
$5  - from promo (10% from sale prices)
https://virtocommerce.atlassian.net/browse/PT-13460
> PT-13460: Discounts are calculated from subtotal

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EnsurePropertyMetadataLoadedMiddleware.cs
fix: NullReferenceException when user get product without properties.
https://virtocommerce.atlassian.net/browse/PT-14534
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.433.0-pr-489-14c1.zip
> PT-14534: NullReferenceException when user get product without properties

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/CreateOrderFromCartCommandHandler.cs
fix: The comment, coupon, and Purchase Order number are not cleared after order creation
https://virtocommerce.atlassian.net/browse/PT-14367
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.438.0-pr-494-0951.zip
> PT-14367: comment, coupon, and purchase order number are not cleared after order creation

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Commands/CreateOrderFromCartCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
fix: DynamicProperties still exist in cart after clearCart or createOrderFrom cart mutations
https://virtocommerce.atlassian.net/browse/PT-14834
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.444.0-pr-500-99e2.zip
> PT-14834: clear cart dynamic properties

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/GraphQLBuilderExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/Validation/ContentTypeValidationRule.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/Validation/CustomFieldsOnCorrectType.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/Validation/CustomKnownArgumentNames.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/Validation/CustomKnownTypeNames.cs
- src/VirtoCommerce.ExperienceApiModule.Web/Module.cs
1. PT-14888. Disabled application/x-www-form-urlencoded ContentType:
if you send raw query where body is formatted as url encoded, for example:
```
query=query%7Bcountries%7Bid%7D%7D
```
and ContentType header is `application/x-www-form-urlencoded` the result will be:
2. PT-14894. Disabled suggestions in errors when the app setting `VirtoCommerce:GraphQLPlayground:Enable` is `false`:
if you send incorrect query, for example:
```
query{countrie{id}}
```
the result will be:
For comparison when  `VirtoCommerce:GraphQLPlayground:Enable` is `true`:
https://virtocommerce.atlassian.net/browse/PT-14888
https://virtocommerce.atlassian.net/browse/PT-14894
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.446.0-pr-503-64ae.zip
> PT-14888,PT-14894: add custom validation rules

- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/CustomerOrderSearchCriteriaBuilder.cs
fix: The range filter in order search can be corrupted if using the date time format. Use encoding. Ex: "createddate:[\"2023-12-01T08:00:00.000Z\" TO \"2023-12-20T08:00:00.000Z\"] otherwise only the date will be taken.
https://virtocommerce.atlassian.net/browse/PT-14841
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.448.0-pr-507-856a.zip
> PT-14841: orders filter can be corrupted

- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/CustomerOrderSearchCriteriaBuilder.cs
- src/XPurchase/VirtoCommerce.XPurchase/VirtoCommerce.XPurchase.csproj
fix: Error when user try to search order by breaking change in Order v3.802. Bump version of order module to v3.802 and refactor CustomerOrderSearchCriteriaBuilder class.
https://virtocommerce.atlassian.net/browse/VCST-329
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.801.0-pr-518-fd35.zip
> VCST-329: Error when user try to search order

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalSearchRequestUserGroupsMiddleware.cs
Usage:
```cs
serviceCollection.AddPipeline<IndexSearchRequestBuilder>(builder =>
{
builder.ReplaceMiddleware(typeof(EvalSearchRequestUserGroupsMiddleware), typeof(EvalSearchRequestUserGroupsMiddlewareExtended));
});
```
https://virtocommerce.atlassian.net/browse/VCST-560
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.808.0-pr-528-7f56.zip
> VCST-560: make EvalSearchRequestUserGroupsMiddleware virtual

- src/VirtoCommerce.ExperienceApiModule.Core/Queries/SlugInfoQueryHandler.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/PageItem.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetSinglePageQuery.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetSinglePageQueryHandler.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Schemas/ContentSchema.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Schemas/PageType.cs
fix: Resolves seo by slug with empty store.
feat: Adds page query that allows request page content by id.
feat: Extends pages query with content property.
```graphql
query{
pages(storeId: "B2B-store", keyword: "Test" ) {
totalCount
items{ permalink relativeUrl name id content }
}
}
```
```graphql
query{
page(storeId: "B2B-store", id: "QjJCLXN0b3JlOjpwYWdlczo6L2hvbWVwYWdlLnBhZ2U-" ) {
id name content
}
}
```
https://virtocommerce.atlassian.net/browse/VCST-566
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.811.0-pr-536-ddfe.zip
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.811.0-pr-536-4c01.zip
> VCST-566: Resolve seoslug with empty store.

- src/VirtoCommerce.ExperienceApiModule.Core/Models/ProductPrice.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/GetStoreQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/ModuleSetting.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/ModuleSettings.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/StoreSettings.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/ModuleSettingType.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/ModuleSettingsType.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/ScalarTypes/ModuleSettingValueGraphType.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/StoreSettingsType.cs
- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
feat:  Expanded store settings query to include installed modules and public store settings for each module. This enhancement enables frontend applications to efficiently access module settings.
Set the store platform setting to true to ensure accessibility and visibility of settings across the store query in XAPI. Example of the modules with public settings: Google Analytics, Hotjar, etc.
```graphql
query{
store(storeId: "B2B-store", cultureName: "en-US") {
storeId
settings {
modules { moduleId settings { name value } }
}
}
}
```
https://virtocommerce.atlassian.net/browse/VCST-596
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.812.0-pr-535-6563.zip
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.812.0-pr-535-8460.zip
> VCST-596: Extend store settings with installed module id and public settings

- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetPageQueryHandler.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/Queries/GetSinglePageQueryHandler.cs
- src/XCMS/VirtoCommerce.ExperienceApiModule.XCMS/VirtoCommerce.ExperienceApiModule.XCMS.csproj
feat: Added Content Type filter to enable filtering by pages. It prevents from retrieving blogs via page query.
https://virtocommerce.atlassian.net/browse/VCST-689
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.812.0-pr-537-6acb.zip
> VCST-689: Add ContentType filter for pages

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Index/IndexSearchRequestBuilder.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQueryHandler.cs
fix: Adds CertainDate Filter to for product search in xapi if First listed and Listing expires are configured for product.
https://virtocommerce.atlassian.net/browse/VCST-541
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.814.0-pr-538-9ac8.zip
> VCST-541: Product StartDate and endDate for product does not work in xapi

- src/XPurchase/VirtoCommerce.XPurchase/Commands/MergeCartCommand.cs
- src/XPurchase/VirtoCommerce.XPurchase/Commands/MergeCartCommandHandler.cs
- src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputMergeCartType.cs
fix: The anonymous cart is not cleared after merge. After the fix, the mutation will delete second cart after merge by default. Added mutation option deleteAfterMerge: bool. By default, true.
https://virtocommerce.atlassian.net/browse/VCST-818
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.815.0-pr-539-3613.zip
> VCST-818: Delete Second cart after merge

- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Queries/SearchProductQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/VirtoCommerce.XDigitalCatalog.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
fix: Fixed the issue where the price range aggregation property was not being included in the response of the /api/catalog/search/products. Depend from catalog 3.807
https://virtocommerce.atlassian.net/browse/VCST-881
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.820.0-pr-543-022b.zip
> VCST-881:PriceRange Aggregation is not functioning as expected.

- src/XPurchase/VirtoCommerce.XPurchase/Extensions/RewardExtensions.cs
fix: The effect off X cart subtotal, no more than Y does not take an account the selected items in cart.
https://virtocommerce.atlassian.net/browse/VCST-661
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.821.0-pr-544-3389.zip
> VCST-661: The effect off X cart subtotal, no more than Y does not take an account the selected items in cart

- src/VirtoCommerce.ExperienceApiModule.Core/VirtoCommerce.ExperienceApiModule.Core.csproj
- src/VirtoCommerce.ExperienceApiModule.Web/Extensions/HttpContextExtensions.cs
- src/VirtoCommerce.ExperienceApiModule.Web/module.manifest
feat: Adds the capability to perform login-on-behalf (impersonation) using token authentication within the XAPI framework. The new feature extends the /connect/token flow by adding support for a custom grant type called impersonate. Users can now leverage the grant_type=impersonate&user_id={user_id} parameter to set the vc_xapi_impersonated_customerid for impersonation purposes. Ensure that the account initiating the impersonation has the necessary platform:security:loginOnBehalf permission. To reset the impersonation , use the grant_type=impersonate and empty user_id.
https://virtocommerce.atlassian.net/browse/VCST-934
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.822.0-pr-546-5199.zip
> VCST-1047: login-on-begalf for token auth

- src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/CustomGraphQLExecuter.cs
Currently AI logs all graphql request for operation id is generated a unique identifier for a span in the context of distributed tracing, following the W3C Trace Context specification https://www.w3.org/TR/trace-context/. The generated span ID helps track the execution flow across different services or components in a distributed system.  
After this changes each /graphql will be logged  within single operation, this will simplify logs reading process and produces correct performance requests counters
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.823.0-pr-547-fc33.zip
> Log POST /graphql requests per one operation (one request - one operation)

- src/VirtoCommerce.ExperienceApiModule.Core/ModuleConstants.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/GetStoreQueryHandler.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Queries/StoreSettings.cs
- src/VirtoCommerce.ExperienceApiModule.Core/Schemas/StoreSettingsType.cs
- src/VirtoCommerce.ExperienceApiModule.Web/Localizations/en.VirtoCommerce.ExperienceApi.json
```graphql
query {
store(storeId: "b2b-store") {
settings {
environmentName
}
}
}
```
https://virtocommerce.atlassian.net/browse/VCST-1273
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.830.0-pr-556-0d70.zip
> VCST-1273: Add environment name to store settings

- src/VirtoCommerce.ExperienceApiModule.Core/Extensions/SeoInfosExtensions.cs
fix: Seo info has been missing on the product page since 3.834.0
https://virtocommerce.atlassian.net/browse/VCST-1473
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.838.0-pr-562-ed8b.zip
> VCST-1473: Seo info is missing on product page
